<?php //Don't add START and END comments ?>
<?php if (!empty($data)): ?>
<div class="truncate-field">
  
  <?php
    $cnt = 0;
    foreach ($data as $author): ?>
    <?php
      $url = $this->record($this->driver)->getLink('author', $author['name']);
      $label = $this->escapeHtml($author['name']);
      $authorityLink = null;
      if (!empty($author['id'])) {
        $authorityLink = $this->authority()->link(
          $url, $label, $author['id'], $author['type'], $this->driver
        );
      }
    ?>
    <?php if (!empty($authorityLink)): ?><?=$authorityLink?><?php else: ?><?=($cnt++ > 0 ? '<br/>' : '')?><a href="<?=$url?>"><?=$label?></a><?php if (!empty($author['date'])): ?><span class="author-date">, <?=$this->escapeHtml($author['date']) ?></span><?php endif; ?><?php endif; ?>
  <?php endforeach; ?>
</div>
<?php endif; ?>
