<!-- START of: finna - search/home/home-3.phtml -->
<div class="info-col">
    <div class="finna-introduction text-center">
        <img src="themes/custom/images/finna-slogan-en.png" alt="Finna – For seekers of information and inspiration" width="300px" height="134px"/>
        <p>Finna.fi is a search service that provides information from Finnish archives, libraries and museums. Content providers have their own <a href="Content/about">Finna websites</a> in addition to this national search service.</p>
    </div>
</div>
<div class="info-col">
    <div class="finna-about">
        <div class="text-center">
            <h3>You can get all of this by logging into Finna.fi</h3>
        </div>
        <div class="about-container">
            <img src="themes/custom/images/share.png" width="64px" height="64px" aria-hidden="true">
            <span>You can save and share your favorite materials</span>
        </div>
        <div class="about-container">
            <img src="themes/custom/images/library.png" width="64px" height="64px" aria-hidden="true">
            <span>You can renew loans and reserve material from various libraries all in one place</span>
        </div>
        <div class="about-container">
            <img src="themes/custom/images/history.png" width="64px" height="64px" aria-hidden="true">
            <span>You can save your search history</span>
        </div>
        <div class="text-center">
            <a href="<?=$this->url('myresearch-userlogin')?>" class="btn btn-primary btn-uppercase" data-lightbox data-lightbox-onclose="window.location.href='<?=$this->escapeHtmlAttr($this->url('myresearch-home')) ?>'" title="<?=$this->transEsc("Login")?>"><i class="fa fa-sign-in fa-lg" aria-hidden="true"></i> <span class="login-text"><?=$this->transEsc("Login")?></span></a>
        </div>
    </div>
</div>
<!-- END of: finna - search/home/home-3.phtml -->