<!-- START of: finna - layout/Additions/header-navibar.phtml -->
<li class="custom">
  <a href="https://www.facebook.com/finnapalvelu" target="_blank"><i class="fa fa-facebook-button"></i><span class="sr-only visible-md visible-lg"><?=$this->transEsc('Finna on Facebook'); ?></span></a>
  <a href="https://www.instagram.com/finna.fi" target="_blank"><i class="fa fa-instagram"></i><span class="sr-only visible-md visible-lg"><?=$this->transEsc('Finna on Instagram'); ?></span></a>
  <a href="https://www.youtube.com/channel/UCjZf-hMtbx1CUK65gIiYjKw" target="_blank"><i class="fa fa-youtube-play"></i><span class="sr-only visible-md visible-lg"><?=$this->transEsc('Finna on Instagram'); ?></span></a>
  <a href="https://twitter.com/finnafi" target="_blank"><i class="fa fa-twitter"></i><span class="sr-only visible-md visible-lg"><?=$this->transEsc('Finna on Twitter'); ?></span></a>
</li>
<!-- END of: finna - layout/Additions/header-navibar.phtml -->
