<!-- START of: finna - content/accessibility-statement_fi.phtml -->
<?php $this->headTitle($this->translate('accessibility_statement'));  ?>
<div class="page-content">
    <h1>Finna.fi-sivuston saavutettavuusseloste</h1>
    <p>Tämä saavutettavuusseloste koskee finna.fi-sivustoa ja on laadittu 8.11.2019. Tämän digipalvelun saavutettavuuden on arvioinut Annanpura Oy (19.6.2019).</p>
    <p>Käyttöliittymän saavutettavuudesta vastaa Kansalliskirjasto. Finna.fi-hakupalvelun sisältämien aineistojen saavutettavuudesta vastaavat aineistoja Finnassa tarjoavat organisaatiot.</p>
    <h2>Digipalvelun saavutettavuuden tila</h2>
    <p>Sivusto täyttää kriittiset saavutettavuusvaatimukset.</p>
    <h2>Huomasitko saavutettavuuspuutteen digipalvelussamme? Kerro se meille ja teemme parhaamme puutteen korjaamiseksi.</h2>
    <h3>Käyttöliittymän saavutettavuuspuutteista ilmoittaminen</h3>
    <h4>Verkkolomakkeella</h4>
    <p><a href="<?=$this->url('feedback-home') ?>">Anna saavutettavuuspalautetta tällä verkkolomakkeella</a>. Valitse palautteen aiheeksi saavutettavuus.</p>
    <h4>Sähköpostilla</h4>
    <p>finna-palaute(at)helsinki.fi</p>
    <h3>Aineistojen saavutettavuuspuutteista ilmoittaminen</h3>
    <h4>Verkkolomakkeella</h4>
    <p>Voit ilmoittaa aineistoihin liittyvistä saavutettavuuspuutteista aineiston yhteydessä olevan Ota yhteyttä-painikkeen kautta. Valitse palautteen aiheeksi saavutettavuus.</p>
    <h2>Valvontaviranomainen</h2>
    <p>Jos huomaat sivustolla saavutettavuusongelmia, anna ensin palautetta meille eli sivuston ylläpitäjälle. Vastauksessa voi mennä 14 päivää. Jos et ole tyytyväinen saamaasi vastaukseen tai et saa vastausta lainkaan kahden viikon aikana, voit tehdä ilmoituksen Etelä-Suomen aluehallintovirastoon. Etelä-Suomen aluehallintoviraston sivulla kerrotaan tarkasti, miten ilmoituksen voi tehdä ja miten asia käsitellään.</p>
    <h3>Valvontaviranomaisen yhteystiedot</h3>
    <p>Etelä-Suomen aluehallintovirasto<br>
    Saavutettavuuden valvonnan yksikkö<br>
    <a href="https://www.saavutettavuusvaatimukset.fi">www.saavutettavuusvaatimukset.fi</a><br>
    saavutettavuus(at)avi.fi<br>
    puhelinnumero vaihde 0295 016 000
    </p>
</div>
<!-- END of: finna - content/accessibility-statement_fi.phtml -->