<!-- START of: custom - content/aineistopaketitList_sv.phtml -->
<div class="aineistopaketti-list">
    <div class="img-box">
      <a href="<?=$this->url('content-page', ['page' => 'kuuntele-suomenruotsia'])?>">
      <img src="../themes/custom/images/luokkahuone/kuuntele-suomenruotsia.png" alt />
      <div class="transparent-box">
        <div class="caption">
          <p><strong>Lyssna på dialekter och talspråk</strong>
          <br>(högstadier, gymnasier; modersmålet)
          </p>
        </div>
      </div> 
            </a>
    </div>
  <div class="img-box">
      <a href="<?=$this->url('content-page', ['page' => 'mainoskuvastoa'])?>">
      <img src="../themes/custom/images/luokkahuone/mainospaketti.jpg" alt />
      <div class="transparent-box">
        <div class="caption">
          <p><strong>Reklam från tiden efter krigen</strong>
          <br>(högstadier, gymnasier)
          </p>
        </div>
      </div> 
            </a>
    </div>
  
  <div class="img-box">
    <a href="<?=$this->url('content-page', ['page' => 'esihistorian-mysteeriesineet'])?>">
      <img src="../themes/custom/images/luokkahuone/esihistorian-mysteeriesineet.jpg" alt />
      <div class="transparent-box">
        <div class="caption">
          <p><strong>Förhistoriens mystiska föremål på Nationalmuseet</strong>
            <br>(lågstadier, gymnasier)
          </p>
        </div>
      </div> 
    </a>
  </div>
  <div class="img-box">
    <a href="<?=$this->url('content-page', ['page' => 'entisaikojen-leikit'])?>">
      <img src="../themes/custom/images/luokkahuone/leikit.jpg" alt />
      <div class="transparent-box">
        <div class="caption">
          <p><strong>Lekar från förr</strong>
            <br>(lågstadier, högstadier)
          </p>
        </div>
      </div> 
    </a>
  </div>
  <div class="img-box">
    <a href="<?=$this->url('content-page', ['page' => 'vanhat-ammatit'])?>">
      <img src="../themes/custom/images/luokkahuone/vanhat-ammatit.jpg" alt="" />
      <div class="transparent-box">
        <div class="caption">
          <p><strong>Gamla yrken</strong>
            <br>(lågstadier, högstadier)
          </p>
        </div>
      </div>
    </a>
  </div>
  <div class="img-box">
    <a href="<?=$this->url('content-page', ['page' => 'siirtolaisuus-valtameren-yli'])?>">
      <img src="../themes/custom/images/luokkahuone/siirtolaisuus.jpg" alt="" />
      <div class="transparent-box">
        <div class="caption">
          <p><strong>Emigrationen över världshaven i början av 1900-talet</strong>
            <br>(högstadier, gymnasier; historia)
          </p>
        </div>
      </div>
    </a>
  </div>
  <div class="img-box">
    <a href="<?=$this->url('content-page', ['page' => 'meri-ihminen'])?>">
      <img src="../themes/custom/images/luokkahuone/meri-ihminen.jpg" alt="" />
      <div class="transparent-box">
        <div class="caption">
          <p><strong>Havet och människan</strong>
            <br>(lågstadier, högstadier, gymnasier)
          </p>
        </div>
      </div>
    </a>
  </div>
  
  <div class="img-box">
    <a href="<?=$this->url('content-page', ['page' => 'kolttasaamelaisten-historiaa'])?>">
      <img src="../themes/custom/images/luokkahuone/kolttasaamelaisten-historiaa.jpg" alt="" />
      <div class="transparent-box">
        <div class="caption">
          <p><strong>Om skoltsamernas historia</strong>
            <br>(lågstadier, högstadier, gymnasier)
          </p>
        </div>
      </div>
    </a>
  </div>
  <div class="img-box">
    <a href="<?=$this->url('content-page', ['page' => 'suomi-vanhoissa-kartoissa'])?>">
      <img src="../themes/custom/images/luokkahuone/suomi-vanhoissa-kartoissa.jpg" alt="" />
      <div class="transparent-box">
        <div class="caption">
          <p><strong>Finland på gamla kartor</strong>
            <br>(lågstadier, gymnasier)
          </p>
        </div>
      </div>
    </a>
  </div>
  <div class="img-box">
    <a href="<?=$this->url('content-page', ['page' => 'suojeluskuntatoiminta-suomessa'])?>">
      <img src="../themes/custom/images/luokkahuone/suojeluskuntatoiminta-suomessa.jpg" alt="" />
      <div class="transparent-box">
        <div class="caption">
          <p><strong>Skyddskårernas verksamhet i Finland</strong>
            <br>(högstadier, gymnasier; historia)
          </p>
        </div>
      </div>
    </a>
  </div>
  <div class="img-box">
    <a href="<?=$this->url('content-page', ['page' => 'tyolaiset'])?>">
      <img src="../themes/custom/images/luokkahuone/tyolaiset.jpg" alt="" />
      <div class="transparent-box">
        <div class="caption">
          <p><strong>Arbetarna börjar påverka samhällsfrågorna i Finland</strong>
            <br>(högstadier, gymnasier; historia)
          </p>
        </div>
      </div> 
    </a>
  </div>
  <div class="img-box">
    <a href="<?=$this->url('content-page', ['page' => 'talvisota'])?>">
      <img src="../themes/custom/images/luokkahuone/talvisota.jpg" alt="" />
      <div class="transparent-box">
        <div class="caption">
          <p><strong>Försvarsmaktens bildmaterial från vinterkriget</strong>
          <br>(högstadier, gymnasier; historia)
          </p>
        </div>
      </div> 
    </a>
  </div>
  <div class="img-box">
    <a href="<?=$this->url('content-page', ['page' => 'kontio'])?>">
      <img src="../themes/custom/images/luokkahuone/kontio.jpg" alt="" />
      <div class="transparent-box">
        <div class="caption">
          <p><strong>Björnen i vår bildkultur</strong>
            <br>(högstadier; bildkonst, slöjd)
          </p>
        </div>
      </div> 
    </a>
  </div>
  <div class="img-box">
    <a href="<?=$this->url('content-page', ['page' => 'suomalainen-muotoilu'])?>">
      <img src="../themes/custom/images/luokkahuone/muotoilu.jpg" alt="" />
      <div class="transparent-box">
        <div class="caption">
          <p><strong>Finsk design</strong>
            <br>(högstadier; bildkonst, slöjd)
          </p>
        </div>
      </div> 
    </a>
  </div>
</div>
<!-- END of: custom - content/aineistopaketitList_sv.phtml -->
