<div class="aineistopaketti-list">
   <div class="img-box">
    <a href="<?=$this->url('content-page', ['page' => 'arkea-asumalahiossa'])?>">
    <img src="../themes/custom/images/luokkahuone/asumalahio.jpg" alt />
    <div class="transparent-box">
      <div class="caption">
        <p><strong>Arkea asumalähiössä 1950-luvulla</strong>
        <br>(yläkoulu, lukio)
        </p>
      </div>
     </div> 
    </a>
  </div>
    <div class="img-box">
      <a href="<?=$this->url('content-page', ['page' => 'kuuntele-suomenruotsia'])?>">
      <img src="../themes/custom/images/luokkahuone/kuuntele-suomenruotsia.png" alt />
      <div class="transparent-box">
        <div class="caption">
          <p><strong>Kuuntele suomenruotsalaisia murteita sekä puhekieltä</strong>
          <br>(yläkoulu, lukio; ruotsi)
          </p>
        </div>
      </div> 
            </a>
    </div>
    <div class="img-box">
      <a href="<?=$this->url('content-page', ['page' => 'mainoskuvastoa'])?>">
      <img src="../themes/custom/images/luokkahuone/mainospaketti.jpg" alt />
      <div class="transparent-box">
        <div class="caption">
          <p><strong>Mainoskuvastoa sotien jälkeen</strong>
          <br>(yläkoulu, lukio)
          </p>
        </div>
      </div> 
            </a>
    </div>
    
    <div class="img-box">
      <a href="<?=$this->url('content-page', ['page' => 'esihistorian-mysteeriesineet'])?>">
      <img src="../themes/custom/images/luokkahuone/esihistorian-mysteeriesineet.jpg" alt />
      <div class="transparent-box">
        <div class="caption">
          <p><strong>Esihistorian mysteeriesineitä Kansallismuseossa</strong><br>(alakoulu, lukio)</p>
        </div>
      </div> 
            </a>
    </div>
    <div class="img-box">
      <a href="<?=$this->url('content-page', ['page' => 'entisaikojen-leikit'])?>">
      <img src="../themes/custom/images/luokkahuone/leikit.jpg" alt />
      <div class="transparent-box">
        <div class="caption">
          <p><strong>Entisaikojen leikit</strong><br>(alakoulu, yläkoulu)</p>
        </div>
      </div> 
      </a>
    </div>
    <div class="img-box">
        <a href="<?=$this->url('content-page', ['page' => 'vanhat-ammatit'])?>">
      <img src="../themes/custom/images/luokkahuone/vanhat-ammatit.jpg" alt />
      <div class="transparent-box">
        <div class="caption">
          <p><strong>Vanhat ammatit</strong><br>(alakoulu, yläkoulu)</p>
        </div>
      </div>
      </a>
    </div>
    <div class="img-box">
      <a href="<?=$this->url('content-page', ['page' => 'siirtolaisuus-valtameren-yli'])?>">
      <img src="../themes/custom/images/luokkahuone/siirtolaisuus.jpg" alt />
      <div class="transparent-box">
        <div class="caption">
          <p><strong>1900-luvun alun siirtolaisuus valtamerten yli</strong><br>(yläkoulu, lukio; historia)</p>
        </div>
      </div>
      </a>
    </div>
    <div class="img-box">
      <a href="<?=$this->url('content-page', ['page' => 'meri-ihminen'])?>">
      <img src="../themes/custom/images/luokkahuone/meri-ihminen.jpg" alt />
      <div class="transparent-box">
        <div class="caption">
          <p><strong>Meri ja ihminen</strong><br>(alakoulu, yläkoulu, lukio)</p>
        </div>
      </div> 
      </a>
    </div>
    
    
    <div class="img-box">
      <a href="<?=$this->url('content-page', ['page' => 'kolttasaamelaisten-historiaa'])?>">
      <img src="../themes/custom/images/luokkahuone/kolttasaamelaisten-historiaa.jpg" alt="" />
      <div class="transparent-box">
        <div class="caption">
          <p><strong>Kolttasaamelaisten historiaa</strong><br>(alakoulu, yläkoulu, lukio)</p>
        </div>
      </div> 
      </a>
    </div>
    <div class="img-box">
        <a href="<?=$this->url('content-page', ['page' => 'suomi-vanhoissa-kartoissa'])?>">
      <img src="../themes/custom/images/luokkahuone/suomi-vanhoissa-kartoissa.jpg" alt="" />
      <div class="transparent-box">
        <div class="caption">
          <p><strong>Suomi vanhoissa kartoissa</strong><br>(alakoulu, lukio)</p>
        </div>
      </div> 
            </a>
    </div>
    <div class="img-box">
      <a href="<?=$this->url('content-page', ['page' => 'suojeluskuntatoiminta-suomessa'])?>">
      <img src="../themes/custom/images/luokkahuone/suojeluskuntatoiminta-suomessa.jpg" alt="" />
      <div class="transparent-box">
        <div class="caption">
          <p><strong>Suojeluskuntatoiminta Suomessa</strong><br>(yläkoulu, lukio; historia)</p>
        </div>
      </div>
      </a>
    </div>
    <div class="img-box">
          <a href="<?=$this->url('content-page', ['page' => 'tyolaiset'])?>">
      <img src="../themes/custom/images/luokkahuone/tyolaiset.jpg" alt="" />
      <div class="transparent-box">
        <div class="caption">
          <p><strong>Työläiset mukaan vaikuttamaan Suomen asioihin</strong><br>(yläkoulu, lukio; historia)</p>
        </div>
      </div> 
            </a>
    </div>
    <div class="img-box">
              <a href="<?=$this->url('content-page', ['page' => 'talvisota'])?>">
      <img src="../themes/custom/images/luokkahuone/talvisota.jpg" alt="" />
      <div class="transparent-box">
        <div class="caption">
          <p><strong>Puolustusvoimien talvisodan valokuva-aineistoa</strong><br>(yläkoulu, lukio; historia)</p>
        </div>
      </div>
            </a>
    </div>
    <div class="img-box">
      <a href="<?=$this->url('content-page', ['page' => 'kontio'])?>">
      <img src="../themes/custom/images/luokkahuone/kontio.jpg" alt="" />
      <div class="transparent-box">
        <div class="caption">
          <p><strong>Kontio kuvakulttuurissamme</strong><br>(yläkoulu; kuvataide, käsityö)</p>
        </div>
      </div> 
     </a>
    </div>
    <div class="img-box">
      <a href="<?=$this->url('content-page', ['page' => 'suomalainen-muotoilu'])?>">
      <img src="../themes/custom/images/luokkahuone/muotoilu.jpg" alt="" />
      <div class="transparent-box">
        <div class="caption">
          <p><strong>Suomalainen muotoilu</strong><br>(yläkoulu; kuvataide, käsityö)</p>
        </div>
      </div>
      </a>
    </div>
  </div>
