<!-- START of: custom - content/headertexts_en-gb.phtml -->
<div class="info-box-text">
    <div class="info-text-close"><i class="fa fa-times close-btn"></i></div>
    <p class="header-info-light">Information about the picture:</p>
    <p class="header-info-title">Cafe Regatta</p>
    <p>
       Author: Grünberg Constantin, 1962 <br/>
       Photograph: 	Humalluoto, Rajasaari bridge<br/>
       Location: Helsinki City Museum
    </p>
    <p><a href="<?=$this->url('record'); ?>hkm.HKMS000005:km0000ma6w?lng=en-gb">To the record »</a></p>
</div>
<!-- END of: custom - content/headertexts_en-gb.phtml -->
