<!-- START of: custom - content/headertexts_sv.phtml -->
<div class="info-box-text">
    <div class="info-text-close"><i class="fa fa-times close-btn"></i></div>
    <p class="header-info-light">Information om bildet:</p>
    <p class="header-info-title">Kafé Regatta</p>
    <p>
       Upphovsman:Grünberg Constantin, 1962<br/>
       Fotograf: Hummelgrundet, Råholmen bron. <br/>
       Belägenhet: Helsingfors stadsmuseum
    </p>
    <p><a href="<?=$this->url('record'); ?>hkm.HKMS000005:km0000ma6w?lng=sv">Till posten »</a></p>
</div>
<!-- END of: custom - content/headertexts_sv.phtml -->
