<!-- START of: national - content/headertexts_fi.phtml -->
<div class="info-box-text">
    <div class="info-text-close"><i class="fa fa-times close-btn"></i></div>
    <p class="header-info-light">Kuvan tiedot:</p>
    <p class="header-info-title">Kahvila Regatta</p>
    <p>
       Valokuvaaja: Grünberg Constantin<br/>
       Kuva: Kahvila Regatta. Humalluodoilla, Rajasaaren sillan kupeessa.<br/>
       Sijainti: Helsingin kaupungin museo
       
    </p>
    <p><a href="<?=$this->url('record'); ?>hkm.HKMS000005:km0000ma6w">Aineistotietoon »</a></p>
</div>
<!-- END of: national - content/headertexts_fi.phtml -->
