<!-- START of: finna - content/kirjastojarjestelma-muutokset-2019-2020_fi.phtml -->
<?php $this->headTitle($this->translate('Korkeakoulujen kirjastojärjestelmävaihdokset'));  ?>
<div class="page-content">
    <h1>Korkeakoulujen kirjastojärjestelmävaihdokset tuovat muutoksia Finna.fi-hakupalvelun käyttöön</h1>
    <p>Vuodenvaihteessa 2019-2020 seuraavien korkeakoulujen kirjastot vaihtavat kirjastojärjestelmänsä:</p>
    <ul class="list-bullets">
        <li>Itä-Suomen yliopiston kirjasto</li>
        <li>Karelia-ammattikorkeakoulun kirjasto</li>
        <li>Satakunnan ammattikorkeakoulun kirjasto</li>
        <li>Seinäjoen ammattikorkeakoulun kirjasto</li>
        <li>Tampereen yliopiston kirjasto</li>
        <li>Turun ammattikorkeakoulun kirjasto</li>
        <li>Turun yliopiston kirjasto</li>
        <li>Åbo Akademin kirjasto</li>
    </ul>
    <p><strong>Jos olet käyttänyt valtakunnallisessa Finna.fi-hakupalvelussa kirjautumiseen jonkin edellä mainitun kirjaston korttia, poistuu nykyinen Finna-tilisi käytöstä 13.12.2019.</strong> Tilin poistuminen johtuu siitä, että järjestelmävaihdoksen jälkeen kyseistä korttia ei enää voi käyttää kirjautumiseen. <strong>Jos olet tallettanut tilillesi hakuja tai listoja suosikkiaineistoistasi, ota ne talteen viimeistään 13.12.2019.</strong> Voit palauttaa suosikit kirjastojen käyttökatkojen jälkeen 7.1.2020, kun rekisteröidyt uudelleen hakupalveluun.  Kirjautumisen yhteydessä järjestelmä luo sinulle uuden Finna-tilin. Vaihtoehtoisesti voit heti luoda itsellesi uuden Finna-tilin käyttämällä kirjautumiseen <a href="/MyResearch/Account?auth_method=Database">Finna-tunnusta</a>.</p>
    <p><strong>Jos olet käyttänyt kirjautumiseen HAKA-tunnusta tai erillistä Finna-tunnusta, tilisi ja sen sisältämät tiedot säilyvät ilman erityisiä toimenpiteitä.</strong></p>
    <p>Huomaa, että kirjastojärjestelmän vaihdoksen vuoksi linkit yllämainittujen kirjastojen aineistoihin eivät enää toimi suosikkilistoissa, vaikka aineiston tiedot ovat muilta osin tallessa.</p>
    <hr style="border-top: 2px solid #723981;">
    <h3>Tampereen yliopiston ja Turun yliopiston kirjastojen kortit lakkaavat toimimasta Finna.fi-hakupalvelussa</h3>
    <p>Yllä kuvattujen muutosten lisäksi Tampereen yliopiston ja Turun yliopiston kirjaston kortit lakkaavat toimimasta valtakunnallisessa Finna.fi-palvelussa 16.12.2019 alkaen. Tämä tarkoittaa, että et voi enää uusia näiden kirjastojen lainoja etkä varata heidän aineistojaan Finna.fi-palvelussa. Muutokset korttien toiminnassa johtuvat siitä, että kirjastojärjestelmän lisäksi myös hakupalvelu vaihtuu molemmissa kirjastoissa. Kuitenkin molempien kirjastojen aineistot ja niiden saatavuustiedot näkyvät Finna.fi-palvelussa järjestelmävaihdosten jälkeen 7.1.2020 alkaen.</p>
    <p>Jos olet käyttänyt Finna.fi:n Finna-tiliisi kirjautumiseen jommankumman kirjaston korttitietoja, voit luoda uuden Finna-tilin käyttämällä Finna-tunnusta, HAKA-kirjautumista tai jonkin toisen kirjaston korttitietoja. Voit sitten liittää tiliin mahdolliset muut korttisi ja tuoda siihen tallentamasi haut ja suosikkilistat.</p>
    <hr style="border-top: 2px solid #723981;">
    <h3>Näin otat talteen suosikkilistasi</h3>
    <ol class="list-numbers">
        <li>Kirjaudu kirjastokortilla ja mene kohtaan Omat tiedot.<br><img src="../themes/custom/images/omat-tiedot.png" alt></li>
        <li>Valitse kohta Lataa suosikit ja haut tiedostona.<br><img src="../themes/custom/images/vienti.png" alt></li>
        <li>Luo joko Finna-tunnus, kirjaudu korkeakoulujen HAKA-tunnuksella tai jonkin toisen kirjaston korttitiedoilla ja tuo suosikit ja haut tiliisi.<br><img src="../themes/custom/images/tuonti.png" alt></li>
    </ol>
    <div class="alert alert-info">Jos tarvitset lisätietoja, ota yhteyttä Kansalliskirjastoon osoitteeseen finna-palaute(at)helsinki.fi.</div>
</div>
<!-- END of: finna - content/kirjastojarjestelma-muutokset-2019-2020_fi.phtml -->