<!-- START of: finna - content/kirjastojarjestelma-muutokset-2019-2020_sv.phtml -->
<?php $this->headTitle($this->translate('Byte av högskolornas bibliotekssystem'));  ?>
<div class="page-content">
    <h1>Byte av högskolornas bibliotekssystem innebär förändringar i användningen av söktjänsten Finna.fi</h1>
    <p>Vid årsskiftet 2019–2020 byter följande högskolors bibliotek till ett nytt bibliotekssystem::</p>
    <ul class="list-bullets">
        <li>Östra Finlands universitetsbibliotek</li>
        <li>Yrkeshögskolan Karelias bibliotek</li>
        <li>Satakunta yrkeshögskolas bibliotek</li>
        <li>Seinäjoki yrkeshögskolas bibliotek</li>
        <li>Tammerfors universitetsbibliotek</li>
        <li>Åbo yrkeshögskolas bibliotek</li>
        <li>Åbo universitetsbibliotek</li>
        <li>Åbo Akademis bibliotek</li>
    </ul>
    <p><strong>Om du har använt något av de ovan nämnda bibliotekens kort för att logga in i den riksomfattande söktjänsten Finna.fi upphör ditt nuvarande Finna-konto att fungera 13.12.2019.</strong> Kontot upphör att fungera eftersom kortet i fråga inte längre kan användas för att logga in i tjänsten efter systembytet.<strong> Om du sparat sökningar eller listor på favoritmaterial på ditt konto ska du ta tillvara dem senast 13.12.2019.</strong> Du kan återställa favoriterna igen 7.1.2020 efter bibliotekens användningsavbrott då du registrerar dig på nytt i söktjänsten. I samband med inloggningen skapar systemet ett nytt Finna-konto åt dig. Alternativt kan du genast skapa ett nytt Finna-konto genom att använda <a href="/MyResearch/Account?auth_method=Database">Finna-användarnamnet</a>.</p>
    <p><strong>Om du har loggat in med HAKA-användarnamn eller ett separat Finna-användarnamn bevaras ditt konto och dess uppgifter utan särskilda åtgärder.</strong></p>
    <p>Notera att bytet av bibliotekssystem innebär att länkar till de ovan nämnda bibliotekens material inte längre fungerar i listor på favoriter, även om materialets uppgifter i övrigt är sparade.</p>
    <hr style="border-top: 2px solid #723981;">
    <h3>Tammerfors universitetsbibliotek och Åbo universitetsbiblioteks kort slutar fungera i söktjänsten Finna.fi</h3>
    <p>Utöver de ovan nämnda förändringarna slutar Tammerfors universitetsbibliotek och Åbo universitetsbiblioteks kort att fungera i den riksomfattande söktjänsten Finna.fi från och med 16.12.2019. Detta innebär att du inte länge kan förnya lån hos dessa bibliotek eller reservera deras material i Finna.fi. Förändringarna i kortens funktion beror på att även söktjänsten byts ut utöver bibliotekssystemet hos båda biblioteken. Båda bibliotekens material och uppgifter om materialets tillgänglighet är dock synliga i Finna.fi efter systembytet från och med 7.1.2020.</p>
    <p>Om du har använt någondera bibliotekets kortuppgifter för att logga in på ditt Finna-konto kan du skapa ett nytt Finna-konto med Finna-användarnamn, HAKA-inloggning eller ett annat biblioteks kortuppgifter. Du kan sedan ansluta eventuella andra kort till kontot och importera sparade sökningar och listor på favoriter.</p>
    <hr style="border-top: 2px solid #723981;">
    <h3>Så här sparar du dina favoriter</h3>
    <ol class="list-numbers">
        <li>Logga in med bibliotekskortet och klicka på Profil.<br><img src="../themes/custom/images/omat-tiedot-sv.png" alt></li>
        <li>Välj Ladda ner favoriter och sökningar som fil.<br><img src="../themes/custom/images/vienti-sv.png" alt></li>
        <li>Skapa ett Finna-användarnamn, logga in med högskolornas HAKA-användarnamn eller ett annat biblioteks kortuppgifter och importera favoriter och sökningar till ditt konto.<br><img src="../themes/custom/images/tuonti-sv.png" alt></li>
    </ol>
    <div class="alert alert-info">För mer information, kontakta Nationalbiblioteket på adressen finna-palaute(at)helsinki.fi.</div>
</div>
<!-- END of: finna - content/kirjastojarjestelma-muutokset-2019-2020_sv.phtml -->