<!-- START of: finna - content/kirjastojarjestelma-muutokset-2019-2020_en.phtml -->
<?php $this->headTitle($this->translate('Changes in the library systems of universities'));  ?>
<div class="page-content">
    <h1>Changes in the library systems of universities affect the use of the Finna.fi search service</h1>
    <p>At the turn of the year, the libraries of the following universities are changing their library systems:</p>
    <ul class="list-bullets">
        <li>University of Eastern Finland Library</li>
        <li>Karelia University of Applied Sciences Library</li>
        <li>Satakunta University of Applied Sciences Library</li>
        <li>Seinäjoki University of Applied Sciences Library</li>
        <li>Tampere University Library</li>
        <li>Turku University of Applied Sciences Library</li>
        <li>Turku University Library</li>
        <li>Åbo Akademi University Library</li>
    </ul>
    <p><strong>If you have logged in to the national Finna.fi search service using a library card from one of the libraries mentioned above, your current Finna account will close on 13 December 2019.</strong> The accounts are being closed because after the system change, the cards can no longer be used to log in to the service.<strong> If you have saved searches or lists concerning your favourite material in your account, please save them in another location by 13 December 2019.</strong> You will be able to restore your favourites after the downtime on 7 January 2020 when you register with the search service again. When logging in, the system will create a new Finna account for you. Alternatively, you can create a new Finna account immediately by logging in using the <a href="/MyResearch/Account?auth_method=Database">Finna ID</a>.</p>
    <p><strong>If you have used a HAKA ID or a separate Finna ID to log in, your account and its data will be retained with no special action required.</strong></p>
    <p>Please note that due to the system change links to material in the libraries mentioned above will no longer work in the favourite lists, although details of the material will remain unchanged in other respects.</p>
    <hr style="border-top: 2px solid #723981;">
    <h3>The library cards for the University of Tampere and the University of Turku will stop working in the Finna.fi search service</h3>
    <p>In addition to the changes described above, the library cards for the University of Tampere and the University of Turku will stop working in the national Finna.fi service from 16 December 2019. This means that you can no longer renew your loans from these libraries. Nor can you reserve their material using the Finna.fi service. The use of cards is changing because the search services of both libraries will change in addition to the library system. However, material and their availability data for both libraries can be accessed from 7 January 2020 via the Finna.fi service after the system change.</p>
    <p>If you have used the card details of either of the libraries to log in to the Finna account of the Finna.fi service, you can create a new Finna account by using the Finna ID, HAKA login or card details related to another library. You can link any other cards to the account and import the searches and favourite lists you have saved there.</p>
    <hr style="border-top: 2px solid #723981;">
    <h3>This is how to save your favourite list</h3>
    <ol class="list-numbers">
        <li>Log in using your library card and select Profile.<br><img src="../themes/custom/images/omat-tiedot-en.png" alt></li>
        <li>Select Download favourites and saved searches.<br><img src="../themes/custom/images/vienti-en.png" alt></li>
        <li>Create a Finna ID, log in using the HAKA ID for universities or the card details of another library, and import your favourites and searches to your account.<br><img src="../themes/custom/images/tuonti-en.png" alt></li>
    </ol>
    <div class="alert alert-info">If you need further information, please contact the National Library of Finland at finna-palaute(at)helsinki.fi.</div>
</div>
<!-- END of: finna - content/kirjastojarjestelma-muutokset-2019-2020_en.phtml -->