<!-- START of: custom - content/lapin-sota_fi.phtml -->
<?php $this->headTitle($this->translate('Puolustusvoimien Lapin sodan valokuva-aineistoa'));?>
<?php if ($this->resolver('luokkahuoneBegin_fi.phtml')): ?>
  <?=$this->render('luokkahuoneBegin_fi.phtml')?>
<?php endif; ?>

<button class="goBack" onclick="goBack()"><i class="fa fa-arrow-left" aria-hidden="true"></i> <?=$this->transEsc('navigate_back') ?></button>

<h2>Puolustusvoimien Lapin sodan valokuva-aineistoa</h2>
<p><strong>Aineistopaketin koonnut:</strong> Sotamuseo
</p>
<p>Sotahistorian opetukseen tarkoitettu aineisto on kerätty Sotamuseon SA-kuva-arkistosta, joka käsittää noin 160 000 sodan ajan Puolustusvoimien rintamavalokuvaajien (TK-kuvaajat) ottamaa valokuvaa vuosien 1939–1945 välisenä aikana. Aineisto on jaettu kolmeksi aineistopaketiksi: talvisota, jatkosota ja Lapin sota. Tähän aineistopakettiin on koottu kuvia Lapin sodasta vuodelta 1945.
</p>
<p>Jatkosodan alussa kesällä 1941 muodostettiin Päämajan alaisuuteen tiedotuskomppanioita (TK), joissa toimi niin kutsuttuja TK-kuvaajia. Mallia otettiin Saksan propagandakomppanioista. Kuvaajien tehtävänä oli tallentaa taistelutilanteiden ohella sotahistoriallista ja kansatieteellistä aineistoa. Kuva-aineistolla tuettiin ja vaikutettiin mielialoihin niin koti- kuin sotarintamalla ja monia kuvia julkaistiin tuon ajan aikakausi- ja sanomalehdissä.
</p>
<p>Kuvia käytettäessä on hyvä pitää mielessä kuvaustoiminnan ja kuvien alkuperäinen tarkoitus. Kuvastekstit ovat valokuvaajien kirjoittamia alkuperäisiä selosteita, ja niitä tulisi lukea ajan hengen tuotoksina. Teksteissä käytetään varsin värikästä kieltä ja joukossa voi olla myös halventavia sanavalintoja. Niin ikään on hyvä pitää mielessä se, että osa kuvista on lavastettu tai muutoin aseteltuja.
</p>
<p>Kuva-aineistoa voi käyttää historian tapahtumien visualisointiin ja tuon ajanjakson elämään tutustumiseen. Valokuvat ovat myös oiva aineisto medialukutaidon opetukseen. Propagandatuotteina ne toimivat hyvänä esimerkkinä siitä, miten kuvallisella viestinnällä voidaan vaikuttaa mielialoihin ja mielipiteisiin.
</p>
<h3>Kohderyhmä:</h3>
<div class="panel-group" id="accordion-kohderyhma" role="tablist" aria-multiselectable="true">
  <div class="panel panel-default">
    <div class="panel-heading" role="tab" id="heading-ylakoulu">
      <h4 class="panel-title">
        <a role="button" data-toggle="collapse" data-parent="#accordion-kohderyhma" href="#ylakoulu">
          Yläkoulu: <small><strong>historia</strong></small>
        </a>
      </h4>
    </div>
    <div id="ylakoulu" class="panel-collapse collapse" role="tabpanel" aria-labelledby="heading-ylakoulu">
      <div class="panel-body">
         <p>Oppiaineiden sisältöalueet:</p>
          <ul class="content-list">
              <li>Historia: S3 Suomea luodaan, rakennetaan ja puolustetaan, S4 Suurten sotien aika</li>
        </ul>
        <p>Tavoite: Kuva-aineistoa voi käyttää historian tapahtumien visualisointiin ja tuon ajanjakson elämään tutustumiseen. Valokuvat ovat myös oiva aineisto medialukutaidon opetukseen. Propagandatuotteina ne toimivat hyvänä esimerkkinä siitä, miten kuvallisella viestinnällä voidaan vaikuttaa mielialoihin ja mielipiteisiin.
        </p>
      </div>
    </div>
    </div>
      <div class="panel panel-default">
    <div class="panel-heading" role="tab" id="heading-lukio">
      <h4 class="panel-title">
        <a role="button" data-toggle="collapse" data-parent="#accordion-kohderyhma" href="#lukio" >
          Lukio: <small><strong>historia</strong></small>
        </a>
      </h4>
    </div>
    <div id="lukio" class="panel-collapse collapse" role="tabpanel" aria-labelledby="heading-lukio">
      <div class="panel-body">
        <p>Oppiaineet ja kurssit:</p>
          <ul class="content-list">
              <li>Historia: HI3 Itsenäisen Suomen historia</li>
           </ul>
        <p>Tavoite: Kuva-aineistoa voi käyttää historian tapahtumien visualisointiin ja tuon ajanjakson elämään tutustumiseen. Valokuvat ovat myös oiva aineisto medialukutaidon opetukseen. Propagandatuotteina ne toimivat hyvänä esimerkkinä siitä, miten kuvallisella viestinnällä voidaan vaikuttaa mielialoihin ja mielipiteisiin.
        </p>
      </div>
    </div>
  </div>
</div>
<ul class="nav nav-tabs help-tabs nav-aineistopaketit">
  <li class="active"><a data-toggle="tab" href="#aineistopaketti">Aineisto</a>
  </li>
</ul>
<div class="tab-content">
  <div id="aineistopaketti" class="tab-pane fade in active">
    <p>Kuvat on järjestetty paikkakunnittain alkaen Lapin evakuoinnista ja Tornion maihinnoususta jatkuen Kemin, Rovaniemen ja Muonion valtauksiin. Tiedotuskomppanioiden valokuvaajat kulkivat saksalaisten jäljessä, joten kuvia saksalaisista itse hävitystyössä ei ole.
    </p>
    <?=$this->userlistEmbed(['id' => 703635, 'view' => 'grid', 'title' => false,  'description' => false, 'date' => false, 'allowCopy' => true])?>
    <div class="panel panel-default">
      <div class="panel-body">
        <h3>Vinkkejä vastaavan aineiston hakemiseen</h3>
        <p>Kaipaatko lisää aineistoa talvisodan käsittelyyn Sotamuseon aineistoista? Etsi vastaavaa aineistoa <a href="/">Finna.fi</a>-hakupalvelusta seuraavin keinoin:
        </p>
        <p><strong>Hakusana:</strong> Hae aineistopaketin aineistojen otsikoista löytyvillä hakusanoilla, esimerkiksi ”ilmatorjunta” tai ”lotta OR lotat”.
        </p>
        <p><strong>Organisaatio:</strong> Valitse organisaatioksi Sotamuseo.
        </p>
        <p><strong>Parhaat rajaimet:</strong> Rajaa tuloksia valitsemalla <strong>Verkossa saatavilla</strong> olevaa aineistoa. Rajaa aineisto koskemaan talvisotaa valitsemalla <strong>Valmistusvuosi</strong>-valikosta itseäsi kiinnostavat vuodet.
        </p>
        <p><strong>Lisätietoja aineistoista:</strong> Mikäli kaipaat lisätietoja tietystä aineistosta, löydät sen <a href="http://sa-kuva.fi">www.sa-kuva.fi</a> -palvelusta.
        </p>
      </div>
    </div>
  </div>
</div>
<!-- END of: custom -  content/lapin-sota_fi.phtml -->