<!-- START of: custom - content/luokkahuone-palaute_sv.phtml -->
<?php $this->headTitle($this->translate('tabs_luokkahuone-palaute'));?>
<?php if ($this->resolver('luokkahuoneBegin_fi.phtml')): ?>
  <?=$this->render('luokkahuoneBegin_fi.phtml')?>
<?php endif; ?>
<?php if ($this->resolver('content/luokkahuone-tabs.phtml')): ?>
  <?=$this->render('content/luokkahuone-tabs.phtml', ['activeTab' => 'luokkahuone-palaute'])?>
<?php endif; ?>
<div class="sidebar left">
  <div class="content-navigation-menu">
  </div>
</div>
<div class="mainbody right">
  <div id="begin1" class="content-section">
    <h2>Delta i utvecklingen av Finna Klassrum!</h2>
    <p>Finna Klassrum utvecklas för lärarnas och skolornas behov. Vi vill bygga upp Finna Klassrum till en nyttig, inspirerande och fungerande webbplats som stöder undervisning och inlärning. Berätta för oss vad som var intressant och nyttigt och hur de olika funktionerna fungerade. Responsen hjälper oss att fokusera på och förbättra egenskaper som är till nytta och intressanta för lärare.
    </p>
    <p><a href="https://link.webropolsurveys.com/S/34D82B443E824081" class="btn btn-primary" role="button">Responsblankett</a>
    </p>
  </div>
  <div id="begin2" class="content-section">
    <h2>Förslag till nytt innehåll</h2>
    <h3>Förslag till nya materialpaket:</h3>
    <p>Har du något undervisningstema för vilket du gärna vill ha tillförlitligt och intressant material eller lärostoff? Föreslå ett tema som du önskar se som färdigt materialpaket i Finna Klassrum. Vi väljer halvårsvis några teman som vi lägger fram för bearbetning till de museer, arkiv och bibliotek som hör till Finna. Vi vidarebefordrar också önskemål om mindre materialpaket.
    </p>
    <h3>Förslag till instruktioner eller instruktionsvideor:</h3>
    <p>Tyckte du att någon funktion var jobbig? Vill du ha ytterligare instruktioner eller instruktionsvideor för eleverna? Berätta för oss i vilket tema det behövs ytterligare instruktioner.
    </p>
    <p><a href="https://link.webropolsurveys.com/S/803F5E0611651D9B" class="btn btn-primary" role="button">Kom med önskemål</a>
    </p>
  </div>
  <div id="begin3" class="content-section">
    <h2>Delta i lärarpanelen</h2>
    <p>Gör din kompetens och röst hörd! För att kommande materialpaket och uppgifter ska vara nyttiga för skolor bildar vi små lärarpaneler i syfte att utveckla dem. I panelerna får lärare, museer, arkiv och bibliotek fungera som bollplank för varandra. Ett museum kan till exempel fråga en lärare hur perspektivet ska avgränsas i relation till ett visst tema eller hur museets material kan länkas till undervisningen. Vi gör också intervjuer och användbarhetstest för att utveckla Finna Klassrum. Vi ser gärna att lärare i olika ämnen ska delta.
    </p>
    <p><a href="https://link.webropolsurveys.com/S/803F5E0611651D9B" class="btn btn-primary" role="button">Delta i lärarpanelen</a>
    </p>
  </div>
</div>
<!-- END of: custom - content/luokkahuone-palaute_sv.phtml -->