<!-- START of: national - content/luokkahuone-palaute_fi.phtml -->
<?php $this->headTitle($this->translate('Anna palautetta'));?>
<?php if ($this->resolver('luokkahuoneBegin_fi.phtml')): ?>
    <?=$this->render('luokkahuoneBegin_fi.phtml')?>
<?php endif; ?>
<?php if ($this->resolver('content/luokkahuone-tabs.phtml')): ?>
  <?=$this->render('content/luokkahuone-tabs.phtml', ['activeTab' => 'luokkahuone-palaute'])?>
<?php endif; ?>
  <div class="sidebar left">
    <div class="content-navigation-menu">
    </div>
  </div>
  <div class="mainbody right">
        <div id="begin1" class="content-section">
        <h2>Osallistu Finna Luokkahuoneen kehittämiseen!</h2>
        <p>Finna Luokkahuonetta kehitetään opettajien ja koulujen käyttöön. Haluamme luoda Finna Luokkahuoneesta hyödyllisen, innostavan ja toimivan sivuston opetuksen ja oppimisen tueksi. Kerro meille mikä oli sinusta kiinnostavaa sisältöä, minkä koit hyödyllisenä ja miten ominaisuudet toimivat tai eivät toimineet. Palautteen avulla voimme keskittyä opettajia hyödyttäviin ja kiinnostaviin ominaisuuksiin ja niiden parantamiseen.</p>
        <p><a href="https://link.webropolsurveys.com/S/34D82B443E824081" class="btn btn-primary" role="button">Palautelomake</a></p>
    </div>
    <div id="begin2" class="content-section">
        <h2>Toivo uusia sisältöjä</h2>
        <h3>Toivo aineistopaketteja:</h3>
        <p>Onko sinulla mielessä jokin opetettava aihe, johon haluaisit luotettavaa ja kiinnostavaa aineistoa tai opetusmateriaalia? Esitä meille teemaa, josta toivoisit Finna Luokkahuoneeseen valmista aineistopakettia. Valitsemme puolivuosittain muutaman teeman, joita viemme eteenpäin Finnassa mukana olevien museoiden, arkistojen ja kirjastojen työstettäväksi. Välitämme myös pienemmät aineistopakettitoiveet eteenpäin.</p>
        <h3>Toivo ohjeita tai ohjevideoita:</h3>
        <p>Tuntuiko jokin ominaisuus hankalalta? Kaipaatko jostain asiasta lisäohjeita tai ohjevideota, jonka voisit näyttää oppilaille? Kerro meille, mistä aiheesta kaipaisit lisää ohjeistusta.</p>
        <p><a href="https://link.webropolsurveys.com/S/803F5E0611651D9B" class="btn btn-primary" role="button">Esitä toive</a></p>
    </div>
    <div id="begin3" class="content-section">
        <h2>Osallistu opettajapaneeliin</h2>
        <p>Tuo osaamisesi ja äänesi kuuluviin! Jotta tulevat aineistopaketit ja tehtävät olisivat kouluille hyödyllisiä, keräämme pieniä opettajapaneeleita niitä kehittämään. Tarkoituksena on törmäyttää yhteen opettajien ja museoiden, arkistojen sekä kirjastojen asiantuntijuutta. Museo voi esimerkiksi tiedustella opettajalta näkökulman rajausta tiettyyn teemaan tai siihen, millaisiin opetuksen sisältöihin museon kiinnostava aineisto voisi linkittyä. Teemme myös haastatteluja ja käytettävyystestejä Finna Luokkahuoneen kehittämiseksi. Toivomme mukaan eri alojen opettajia.</p>
        <p><a href="https://link.webropolsurveys.com/S/803F5E0611651D9B" class="btn btn-primary" role="button">Osallistu opettajapaneeliin</a></p>
    </div>
</div>
<!-- END of: national - content/luokkahuone-palaute_fi.phtml -->