<!-- START of: custom - content/pienteollisuus-suomessa_sv.phtml -->
<?php $this->headTitle('Småindustrin i Finland från 1930-talet till 1980-talet');?>
<?php if ($this->resolver('luokkahuoneBegin_fi.phtml')): ?>
  <?=$this->render('luokkahuoneBegin_fi.phtml')?>
<?php endif; ?>

<button class="goBack" onclick="goBack()"><i class="fa fa-arrow-left" aria-hidden="true"></i> <?=$this->transEsc('navigate_back') ?></button>

<h2>Småindustrin i Finland från 1930-talet till 1980-talet</h2>
<p><strong>Materialet har sammanställts av</strong> Esbo stadsmuseum
</p>
<p>Esbo stadsmuseum har tagit fram det här materialpaketet för att ge eleven kunskap om småindustrin och dess utveckling i Finland från 1930-talet till 1980-talet. Som fallexempel används Lindholms såg och Köklax glasbruk.
</p>
<h3>Målgrupp:</h3>
<div class="panel-group" id="accordion-kohderyhma" role="tablist" aria-multiselectable="true">
  <div class="panel panel-default">
    <div class="panel-heading" role="tab" id="heading-ylakoulu">
      <h4 class="panel-title">
        <a role="button" data-toggle="collapse" data-parent="#accordion-kohderyhma" href="#ylakoulu">
          Högstadier: <small><strong>historia, samhällslära</strong></small>
        </a>
      </h4>
    </div>
    <div id="ylakoulu" class="panel-collapse collapse" role="tabpanel" aria-labelledby="heading-ylakoulu">
      <div class="panel-body">
        <p>Läroämnens innehållsområden:</p>
        <ul class="content-list">
          <li>Historia: I1 Industrisamhällets uppkomst och utveckling, I3 Finland skapas, byggs och försvaras, I5 Välfärdssamhällets uppbyggnad
          </li>
          <li>Samhällslärä: I1 Vardagskompetens och kontroll över det egna livet, I4 Ekonomisk verksamhet
          </li>
        </ul>
        <p>Mål: Med hjälp av lokala exempel handleda eleven i att analysera kontinuitet och förändring i industrialiseringen av Finland och mer allmänt utifrån en världshistorisk kontext. Hjälpa eleven att utveckla förståelse för ekonomins globalisering i Finland.
        </p>
      </div>
    </div>
    </div>
      <div class="panel panel-default">
    <div class="panel-heading" role="tab" id="heading-lukio">
      <h4 class="panel-title">
        <a role="button" data-toggle="collapse" data-parent="#accordion-kohderyhma" href="#lukio">
          Gymnasier: <small><strong>historia, samhällslära</strong></small>
        </a>
      </h4>
    </div>
    <div id="lukio" class="panel-collapse collapse" role="tabpanel" aria-labelledby="heading-lukio">
      <div class="panel-body">
        <p>Läroämnens kurser:</p>
        <ul class="content-list">
          <li>Historia: HI1 Människan i en föränderlig omvärld, HI3 Det självständiga Finlands historia
          </li>
          <li>Samhällslära: YH1 Det finländska samhället, YH2 Ekonomikunskap
          </li>
        </ul>
        <p>Mål: Med hjälp av lokala exempel handleda eleven i att analysera kontinuitet och förändring i industrialiseringen av Finland och mer allmänt utifrån en världshistorisk kontext. Hjälpa eleven att utveckla förståelse för ekonomins globalisering i Finland.
        </p>
      </div>
    </div>
  </div>
</div>
<div class="panel panel-default">
  <div class="panel-body">
    <h4>Diskussionsförslag på lektioner:</h4>
    <ul class="content-list">
      <li>Hur har utvecklingen av industrin i Finland sett ut mot bakgrund av de båda exemplen?
      </li>
      <li>Hur har industrialiseringen framskridit (från småindustri till dagens stora fabriker)?
      </li>
      <li>Vilka olika typer av industrier framkommer i materialet?
      </li>
      <li>Vilka slags personer har arbetat inom industrin (till exempel analys av klädsel och kön)?
      </li>
    </ul>
  </div>
</div>
<ul class="nav nav-tabs help-tabs nav-aineistopaketit">
  <li class="active"><a data-toggle="tab" href="#aineistopaketti">Material</a>
  </li>
  <li><a data-toggle="tab" href="#tehtavaideat">Uppgiftsidéer</a>
  </li>
</ul>
<div class="tab-content">
  <div id="aineistopaketti" class="tab-pane fade in active">
    <?=$this->userlistEmbed(['id' => 833297, 'view' => 'grid', 'title' => false, 'description' => false, 'date' => false, 'allowCopy' => true])?>
  </div>

  <div id="tehtavaideat" class="tab-pane fade">
    <p>Uppgiftsidéerna ger tips för hur du kan studera materialpaketet. Du kan granska ett tema genom att välja en eller flera uppgifter. Uppgifterna kan utföras individuellt, i par eller grupp. Omarbeta uppgiftsidéerna för olika utbildningsstadier och läroämnen på önskat sätt.
    </p>
    <p>Nyttiga länkar:
    </p>
    <ul class="content-list">
      <li>Statistik om Finlands ekonomiska struktur / industrin i Finland: <a target="_blank" href="https://tilastokeskus.fi/index_sv.html">https://tilastokeskus.fi/index_sv.html</a> , <a target="_blank" href="https://findikaattori.fi/sv">https://findikaattori.fi/sv</a>
      </li>
    </ul>
    <br>
    <div class="panel-group" id="accordion-tehtavaideat" role="tablist" aria-multiselectable="true">
      <div class="panel panel-default">
        <div class="panel-heading" role="tab" id="heading-pienteollisuus">
          <h3 class="panel-title">
            <a class="collapsed" role="button" data-toggle="collapse" data-parent="#accordion-tehtavaideat" href="#pienteollisuus">
              Småindustrin i Finland
            </a>
          </h3>
        </div>
        <div id="pienteollisuus" class="panel-collapse collapse" role="tabpanel" aria-labelledby="heading-pienteollisuus">
          <div class="panel-body">
            <h4>Uppgift 1</h4>
            <p>Ta del av materialhelheten Småindustrin i Finland från 1930-talet till 1980-talet. Ta ställning till påståendet: Finlands industrialisering skedde snabbt, med landsbygden som drivkraft och med tyngdpunkt på skogs- och småindustrin.
            </p>
            <h4>Uppgift 2</h4>
            <p>Undersök bilderna <a target="_blank" href="/Record/ekm.urn:nbn:fi-ekmhttp%253A%252F%252Fwww.profium.com%252Fespoo%252FKohde-8B4F6D48-2A69-F45B-51A5-787F1B3C8C20#image">"Lindholms såg / Lindholmin saha 1939"</a> och <a target="_blank" href="/Record/ekm.urn:nbn:fi-ekmhttp%253A%252F%252Fwww.profium.com%252Fespoo%252FKohde-FF5A559E-EDC9-F47F-BC24-C1CA6CC8308D#image">"Kauklahden lasitehdas vuonna 1948"</a>. Fundera på varför utvecklingen av industrin och trafikförbindelser har varit så nära kopplade till varandra.
            </p>
          </div>
        </div>
      </div>
      <div class="panel panel-default">
        <div class="panel-heading" role="tab" id="heading-lindholmin-saha">
          <h3 class="panel-title">
            <a class="collapsed" role="button" data-toggle="collapse" data-parent="#accordion-tehtavaideat" href="#lindholmin-saha">
              Lindholms såg
            </a>
          </h3>
        </div>
        <div id="lindholmin-saha" class="panel-collapse collapse" role="tabpanel" aria-labelledby="heading-lindholmin-saha">
          <div class="panel-body">
            <h4>Uppgift 1</h4>
            <p>Undersök bilderna <a target="_blank" href="/Record/ekm.urn:nbn:fi-ekmhttp%253A%252F%252Fwww.profium.com%252Fespoo%252Fkohde%252FKohde-B97AF2A6-11B2-E43B-C5D9-554046FEF84C#image">"Lindholms sågens fabriksbrandkår (FBK) framför hyvleriet / Lindholmin sahan tehdaspalokunta höyläämön edessä"</a> och <a target="_blank" href="/Record/ekm.urn:nbn:fi-ekmhttp%253A%252F%252Fwww.profium.com%252Farchive%252FArchivedObject-AAA99FF7-C5D1-E56F-28F5-B05E33881EA8#image">"Lindholms sågs eldsvåda 1977, hyvlerisidan / Lindholmin sahan palo v. 1977, höyläämön puoli"</a>.
            </p>
            <ol class="content-list">
              <li>Vilka risker har förknippats med små sågverk?
              </li>
              <li>Hur har man försökt förebygga riskerna?
              </li>
              <li>Vilka fördelar har större fabriker (företag) med tanke på dessa risker? (Obs. Rikta uppmärksamhet på företagets ekonomi.)
              </li>
            </ol>
            <h4>Uppgift 2</h4>
            <p>Undersök bilden <a target="_blank" href="/Record/ekm.urn:nbn:fi-ekmhttp%253A%252F%252Fwww.profium.com%252Farchive%252FArchivedObject-3D7EE308-DFB2-2F6F-9FDF-17CF0921EAC0#image">"Anställda vid Ab Bröderna Lillqvist / Veljekset Lillqvistin henkilökuntaa"</a>.
            </p>
            <ol class="content-list">
              <li>Vilken ställning tror du att personerna på bilden har haft?
              </li>
              <li>Hur många kvinnor hittar du i bilden och i vilka roller?
              </li>
              <li>Vad tror du att det beror på? Motivera ditt svar.
              </li>
            </ol>
            <h4>Uppgift 3</h4>
            <p>Undersök bilden <a target="_blank" href="/Record/ekm.urn:nbn:fi-ekmhttp%253A%252F%252Fwww.profium.com%252Fespoo%252Fkohde%252FKohde-56EB988F-CA83-39FA-C7B2-56630DA43EB4#image">"Lindholmin sahaa puretaan, elokuu 1987"</a>. Utnyttja nätet och ta reda på hur förutsättningarna för skogsindustrin har förändrats från 1920-talet och framåt. Fundera över varför små- och sågindustrin har minskat markant i Finland under de senaste årtiondena.
            </p>
            <h4>Uppgift 4</h4>
            <p>Titta på bilden <a href="/Record/ekm.urn:nbn:fi-ekmhttp%253A%252F%252Fwww.profium.com%252Fespoo%252FKohde-59DDBC5F-E3B5-22D2-F38B-3CAD666C9E6A#image">"Arbetare på Lindholms såg / Lindholmin sahan työmiehiä"</a>. Sök sedan bilder på nätet av personer som arbetar inom skogsindustrin i dag (använd exempelvis sökorden "forest industry workers" eller liknande). Jämför bilderna med varandra. Hur har arbetet förändrats?
            </p>
          </div>
        </div>
      </div>
      <div class="panel panel-default">
        <div class="panel-heading" role="tab" id="heading-kauklahden-lasi">
          <h3 class="panel-title">
            <a class="collapsed" role="button" data-toggle="collapse" data-parent="#accordion-tehtavaideat" href="#kauklahden-lasi">
              Köklax glasbruk
            </a>
          </h3>
        </div>
        <div id="kauklahden-lasi" class="panel-collapse collapse" role="tabpanel" aria-labelledby="heading-kauklahden-lasi">
          <div class="panel-body">
            <h4>Uppgift 1</h4>
            <p>Undersök bilden <a href="/Record/ekm.urn:nbn:fi-ekmhttp%253A%252F%252Fwww.profium.com%252Fespoo%252FKohde-EE428CFC-8C4A-499C-E6EF-9CDBAC19C9A8#image ">"Kauklahden lasitehdas, maalaamo vuonna 1948"</a>.
            </p>
            <ol class="content-list">
              <li>Bedöm vilka slags personer som arbetar på bilden.
              </li>
              <li>Reflektera över varför arbetarna på bilden har blivit anställda vid fabriken. (SVAR: unga flickor; att måla är ett petnoga arbete à små och noggranna händer en fördel. Dessutom hade andra världskriget precis slutat à familjerna behövde inkomster, all möjlig arbetskraft togs i bruk, en stor del av männen hade stupat.)
              </li>
            </ol>
          </div>
        </div>
      </div>
      <div class="panel panel-default">
        <div class="panel-heading" role="tab" id="heading-vastaukset">
          <h3 class="panel-title">
            <a class="collapsed" role="button" data-toggle="collapse" data-parent="#accordion-tehtavaideat" href="#vastaukset">
              Svar
            </a>
          </h3>
        </div>
        <div id="vastaukset" class="panel-collapse collapse" role="tabpanel" aria-labelledby="heading-vastaukset">
          <div class="panel-body">
            <h4>Lindholms såg</h4>
            <h5>Uppgift 3</h5>
            <ol class="content-list" start="3">
              <li>Omstruktureringar, en stor del av BNP kommer från tjänstesektorn + sågvaror till träförädling = pappers- och annan industri. Bakgrund av globaliseringens inverkan.
              </li>
            </ol>
            <h4>Köklax glasbruk</h4>
            <h5>Uppgift 1</h5>
            <ol class="content-list" start="2">
              <li>Unga flickor; att måla är ett petnoga arbete à små och noggranna händer en fördel. Dessutom hade andra världskriget precis slutat à familjerna behövde inkomster, all möjlig arbetskraft togs i bruk, en stor del av männen hade stupat.
              </li>
            </ol>          
          </div>
        </div>
      </div>
    </div>
  </div>
</div>
<!-- END of: custom - content/pienteollisuus-suomessa_sv.phtml -->