<!-- START of: national - content/pienteollisuus-suomessa_fi.phtml -->
<?php $this->headTitle($this->translate('Pienteollisuus Suomessa 1930-luvulta 1980-luvulle'));?>
<?php if ($this->resolver('luokkahuoneBegin_fi.phtml')): ?>
    <?=$this->render('luokkahuoneBegin_fi.phtml')?>
<?php endif; ?>

<button class="goBack" onclick="goBack()"><i class="fa fa-arrow-left" aria-hidden="true"></i> <?=$this->transEsc('navigate_back') ?></button>

<h2>Pienteollisuus Suomessa 1930-luvulta 1980-luvulle</h2>
<p><strong>Aineistopaketin koonnut:</strong> Espoon kaupunginmuseo</p>
<p>Espoon kaupunginmuseo on koonnut tämän aineistopaketin, jonka kanssa pääset tutustumaan suomalaiseen pienteollisuuteen ja sen kehitykseen 1930-luvulta 1980-luvulle. Tapausesimerkkeinä toimivat Lindholmin saha ja Kauklahden lasi.</p>
<h3>Kohderyhmä:</h3>
<div class="panel-group" id="accordion-kohderyhma" role="tablist" aria-multiselectable="true">
  <div class="panel panel-default">
    <div class="panel-heading" role="tab" id="heading-ylakoulu">
      <h4 class="panel-title">
        <a role="button" data-toggle="collapse" data-parent="#accordion-kohderyhma" href="#ylakoulu">
          Yläkoulu: <small><strong>historia, yhteiskuntaoppi</strong></small>
        </a>
      </h4>
    </div>
    <div id="ylakoulu" class="panel-collapse collapse" role="tabpanel" aria-labelledby="heading-ylakoulu">
      <div class="panel-body">
          <p>Oppiaineiden sisältöalueet:</p>
          <ul class="content-list">
              <li>Historia: S1 Teollisuusyhteiskunnan synty ja kehitys, S3 Suomea luodaan, rakennetaan ja puolustetaan, S5 Hyvinvointiyhteiskunnan rakentaminen</li>
              <li>Yhteiskuntaoppi: S1 Arkielämä ja oman elämän hallinta, S4 Taloudellinen toiminta</li>
          </ul>
          <p>Tavoite: Ohjata opiskelijaa paikallisesimerkkien avulla analysoimaan muutosta ja jatkuvuutta Suomen teollistumisessa ja yleisemmin maailmanhistoriallisessa kontekstissa. Auttaa opiskelijaa ymmärtämään talouden globalisaation merkitystä Suomessa.</p>
      </div>
    </div>
    </div>
      <div class="panel panel-default">
    <div class="panel-heading" role="tab" id="heading-lukio">
      <h4 class="panel-title">
        <a role="button" data-toggle="collapse" data-parent="#accordion-kohderyhma" href="#lukio">
          Lukio: <small><strong>historia, yhteiskuntaoppi</strong></small>
        </a>
      </h4>
    </div>
    <div id="lukio" class="panel-collapse collapse" role="tabpanel" aria-labelledby="heading-lukio">
      <div class="panel-body">
          <p>Oppiaineet ja kurssit:</p>
          <ul class="content-list">
              <li>Historia: HI1 Ihminen ympäristön ja yhteiskuntien muutoksessa, HI3 Itsenäisen Suomen historia</li>
              <li>Yhteiskuntaoppi: YH1 Suomalainen yhteiskunta, YH2 Taloustieto</li>
          </ul>  
          <p>Tavoite: Ohjata opiskelijaa paikallisesimerkkien avulla analysoimaan muutosta ja jatkuvuutta Suomen teollistumisessa ja yleisemmin maailmanhistoriallisessa kontekstissa. Auttaa opiskelijaa ymmärtämään talouden globalisaation merkitystä Suomessa.</p>
      </div>
    </div>
  </div>
</div>
<div class="panel panel-default">
  <div class="panel-body">
<h4>Pohdittavaa oppitunneille:</h4>
<ul class="content-list">
    <li>Miltä suomalaisen teollisuuden kehitys on näyttänyt kahden esimerkin valossa?</li>
    <li>Miten teollistuminen on edennyt (pienteollisuudesta nykyisiin suuriin tehtaisiin)</li>
    <li>Mitä eri teollisuuden muotoja aineistossa esiintyy?</li>
    <li>Keitä teollisuuden parissa on työskennellyt (esim. pukeutumisen ja sukupuolen analysointi)?</li>
</ul>
</div>
</div>
<ul class="nav nav-tabs help-tabs nav-aineistopaketit">
    <li class="active"><a data-toggle="tab" href="#aineistopaketti">Aineisto</a></li>
    <li><a data-toggle="tab" href="#tehtavaideat">Tehtäväideat</a></li>
</ul>
<div class="tab-content">
     <div id="aineistopaketti" class="tab-pane fade in active">
<?= $this->userlistEmbed(['id' => 833297, 'view' => 'grid', 'title' => false, 'description' => false, 'date' => false, 'allowCopy' => true])?>
</div>

 <div id="tehtavaideat" class="tab-pane fade">
     <p>Tehtäväideat on suunniteltu antamaan ideoita siihen, kuinka voit tarkastella aineistopakettia. Voit lähestyä aihetta valitsemalla tehtävistä yhden tai useamman. Tehtävät voi tehdä yksilö-, pari- tai ryhmätehtävinä. Muokkaa tehtäväideoita eri oppiasteisiin ja oppiaineisiin haluamallasi tavalla.</p>
<p>Hyödyllisiä linkkejä:</p>
<ul class="content-list">
    <li>Tilastotietoa Suomen talouden rakenteesta / teollisuudesta: <a target="_blank" href="https://www.tilastokeskus.fi/">https://www.tilastokeskus.fi/</a> , <a target="_blank" href="https://findikaattori.fi/">https://findikaattori.fi/</a></li>
</ul>
<br>
        <div class="panel-group" id="accordion-tehtavaideat" role="tablist" aria-multiselectable="true">
            
  <div class="panel panel-default">
    <div class="panel-heading" role="tab" id="heading-pienteollisuus">
      <h3 class="panel-title">
        <a class="collapsed" role="button" data-toggle="collapse" data-parent="#accordion-tehtavaideat" href="#pienteollisuus">
            Pienteollisuus Suomessa
        </a>
      </h3>
    </div>
    <div id="pienteollisuus" class="panel-collapse collapse" role="tabpanel" aria-labelledby="heading-pienteollisuus">
      <div class="panel-body">
          <h4>Tehtävä 1</h4>
          <p>Tutustu Pienteollisuus Suomessa 1930-luvulta 1980-luvulle -aineistokokonaisuuteen. Ota kantaa väitteeseen: suomalainen teollistuminen tapahtui nopeasti, maaseutuvetoisesti ja painottuen metsä- ja pienteollisuuteen.</p>
          <h4>Tehtävä 2</h4>
          <p>Tarkastele kuvia <a target="_blank" href="/Record/ekm.urn:nbn:fi-ekmhttp%253A%252F%252Fwww.profium.com%252Fespoo%252FKohde-8B4F6D48-2A69-F45B-51A5-787F1B3C8C20#image">”Lindholms såg / Lindholmin saha 1939”</a> ja <a target="_blank" href="/Record/ekm.urn:nbn:fi-ekmhttp%253A%252F%252Fwww.profium.com%252Fespoo%252FKohde-FF5A559E-EDC9-F47F-BC24-C1CA6CC8308D#image">”Kauklahden lasitehdas vuonna 1948”</a>. Pohdi, miksi teollisuuden ja liikenneyhteyksien kehittyminen ovat liittyneet niin keskeisesti yhteen.</p>
       </div>
    </div>
  </div>
  
  <div class="panel panel-default">
    <div class="panel-heading" role="tab" id="heading-lindholmin-saha">
      <h3 class="panel-title">
        <a class="collapsed" role="button" data-toggle="collapse" data-parent="#accordion-tehtavaideat" href="#lindholmin-saha">
            Lindholmin saha
        </a>
      </h3>
    </div>
    <div id="lindholmin-saha" class="panel-collapse collapse" role="tabpanel" aria-labelledby="heading-lindholmin-saha">
      <div class="panel-body">
          <h4>Tehtävä 1</h4>
          <p>Tarkastele kuvia <a target="_blank" href="/Record/ekm.urn:nbn:fi-ekmhttp%253A%252F%252Fwww.profium.com%252Fespoo%252Fkohde%252FKohde-B97AF2A6-11B2-E43B-C5D9-554046FEF84C#image">”Lindholms sågens fabriksbrandkår (FBK) framför hyvleriet / Lindholmin sahan tehdaspalokunta höyläämön edessä”</a> ja <a target="_blank" href="/Record/ekm.urn:nbn:fi-ekmhttp%253A%252F%252Fwww.profium.com%252Farchive%252FArchivedObject-AAA99FF7-C5D1-E56F-28F5-B05E33881EA8#image">”Lindholms sågs eldsvåda 1977, hyvlerisidan / Lindholmin sahan palo v. 1977, höyläämön puoli”</a>.</p>
          <ol class="content-list">
              <li>Mitä riskejä pieniin sahayrityksiin on liittynyt?</li>
              <li>Miten näihin riskeihin on pyritty varautumaan?</li>
              <li>Mitä etuja suuremmissa tehtaissa (yrityksissä) on liittyen näihin riskeihin? (Huom. kiinnitä huomiota yrityksen talouteen.)</li>
          </ol>

          <h4>Tehtävä 2</h4>
          <p>Tarkastele kuvaa <a target="_blank" href="/Record/ekm.urn:nbn:fi-ekmhttp%253A%252F%252Fwww.profium.com%252Farchive%252FArchivedObject-3D7EE308-DFB2-2F6F-9FDF-17CF0921EAC0#image">”Anställda vid Ab Bröderna Lillqvist / Veljekset Lillqvistin henkilökuntaa”</a>.</p>
                    <ol class="content-list">
              <li>Päättele, missä asemassa kukin kuvan henkilö on työskennellyt.</li>
              <li>Montako naista löydät kuvasta ja mistä rooleista?</li>
              <li>Mistä tämä johtuu? Perustele vastauksesi.</li>
          </ol>
          <h4>Tehtävä 3</h4>
          <p>Tarkastele kuvaa <a target="_blank" href="/Record/ekm.urn:nbn:fi-ekmhttp%253A%252F%252Fwww.profium.com%252Fespoo%252Fkohde%252FKohde-56EB988F-CA83-39FA-C7B2-56630DA43EB4#image">”Lindholmin sahaa puretaan, elokuu 1987”</a>. Selvitä verkkoa hyödyntäen, miten Suomen talouden sekä metsäteollisuuden rakenne on muuttunut 1920-luvulta eteenpäin. Pohdi, miksi suomalainen pien- ja sahateollisuus on vähentynyt merkittävästi viime vuosikymmeninä.</p>
          <h4>Tehtävä 4</h4>
          <p>Katso kuvaa <a href="/Record/ekm.urn:nbn:fi-ekmhttp%253A%252F%252Fwww.profium.com%252Fespoo%252FKohde-59DDBC5F-E3B5-22D2-F38B-3CAD666C9E6A#image">”Arbetare på Lindholms såg / Lindholmin sahan työmiehiä”</a>. Etsi sen jälkeen verkosta kuvia metsäteollisuuden parissa nykyään työskentelevistä ihmisistä (kokeile esim. hakusanoja ”forest industry workers” tms.). Vertaile kuvia keskenään. Miten työnteko on muuttunut?</p>
       </div>
    </div>
  </div>
  
    <div class="panel panel-default">
    <div class="panel-heading" role="tab" id="heading-kauklahden-lasi">
      <h3 class="panel-title">
        <a class="collapsed" role="button" data-toggle="collapse" data-parent="#accordion-tehtavaideat" href="#kauklahden-lasi">
            Kauklahden lasi
        </a>
      </h3>
    </div>
    <div id="kauklahden-lasi" class="panel-collapse collapse" role="tabpanel" aria-labelledby="heading-kauklahden-lasi">
      <div class="panel-body">
          <h4>Tehtävä 1</h4>
          <p>Tarkastele kuvaa <a href="/Record/ekm.urn:nbn:fi-ekmhttp%253A%252F%252Fwww.profium.com%252Fespoo%252FKohde-EE428CFC-8C4A-499C-E6EF-9CDBAC19C9A8#image ">”Kauklahden lasitehdas, maalaamo vuonna 1948”</a>.</p>
          <ol class="content-list">
              <li>Arvioi, keitä kuvassa työskentelee.</li>
              <li>Pohdi, miksi tehtaaseen on palkattu kuvassa esiintyviä työntekijöitä. </li>
          </ol>
            </div>
    </div>
  </div>
  
      <div class="panel panel-default">
    <div class="panel-heading" role="tab" id="heading-vastaukset">
      <h3 class="panel-title">
        <a class="collapsed" role="button" data-toggle="collapse" data-parent="#accordion-tehtavaideat" href="#vastaukset">
            Vastaukset
        </a>
      </h3>
    </div>
    <div id="vastaukset" class="panel-collapse collapse" role="tabpanel" aria-labelledby="heading-vastaukset">
      <div class="panel-body">
          <h4>Lindholmin saha</h4>
          <h5>Tehtävä 3</h5>
          <ol class="content-list" start="3">
              <li>Suomen rakennemuutos, valtaosa BKT:stä palveluista ja sahatavaran valmistuksesta puunjalostukseen, eli paperi- ym. teollisuus. Taustalla globalisaation vaikutus.</li>
          </ol>
          <h4>Kauklahden lasi</h4>
          <h5>Tehtävä 1</h5>
          <ol class="content-list" start="2">
              <li>Nuoria tyttöjä; maalaaminen on pikkutarkkaa puuhaa ja pienet, tarkat kädet ovat avuksi. Lisäksi toinen maailmansota on juuri päättynyt ja perheisiin tarvitaan tuloja. Kaikki mahdollinen työvoima on otettava käyttöön, sillä osa miehistä on kuollut sodassa.</li>
          </ol>          
            </div>
    </div>
  </div>
  
  
    </div>
  </div>
</div>
<!-- END of: national -  content/pienteollisuus-suomessa_fi.phtml -->