<!-- START of: national - content/sosialismi_fi.phtml -->
<?php $this->headTitle($this->translate('Sosialismin aatteen levitystyö ja vaalijulisteiden propaganda'));?>
<?php if ($this->resolver('luokkahuoneBegin_fi.phtml')): ?>
    <?=$this->render('luokkahuoneBegin_fi.phtml')?>
<?php endif; ?>

<button class="goBack" onclick="goBack()"><i class="fa fa-arrow-left" aria-hidden="true"></i> <?=$this->transEsc('navigate_back') ?></button>

<h2>Sosialismin aatteen levitystyö ja vaalijulisteiden propaganda</h2>
<p><strong>Aineistopaketin koonnut:</strong> Iris Olavinen & Jani Kaunismäki / Työväen Arkisto</p>
<p>Työväen Arkiston aineistopaketti kertoo, kuinka sosialismin aatetta levitettiin Suomessa 1900-luvun alussa ja millaista oli tuon ajan vaalijulisteiden propaganda. Sosialismin aatteesta intoutuneet sanansaattajat ja agitaattorit veivät sanomaansa vähän (jos ollenkaan) koulunpenkkejä kuluttaneen kansanosan pariin. Tavoite oli herätellä köyhää kansanosaa toimimaan oman asemansa parantamiseksi.</p>
<p>Valtaosa kansasta eli niukkuudessa. Tällä köyhälistöksi kutsutulla kansanosalla ei ollut juurikaan mahdollisuuksia vaikuttaa valtakunnan tai paikalliseen politiikkaan virallisia väyliä pitkin. Heillä ei ollut usein varaa kouluttautumisen kautta nostaa omaa sosiaalista ja taloudellista asemaansa. Suurin osa köyhälistöstä oli teollisuustyöläisiä ja maaseudun maatyöläisiä.</p>
<p>Muutos parempaan saatiin eduskuntauudistuksen myötä. Kaikilla täysi-ikäisillä oli mahdollisuus äänestää, asettua ehdolle ja vaikuttaa yhteisten asioiden järjestämiseen valtakunnan politiikassa. Sosialidemokraattinen puolue tavoitteli erityisesti köyhälistön ääniä. Eduskuntavaalityössä käytetty kieli oli tuolloin yksinkertaista ja propagandistista.</p>
<p>Kaikki Työväen Arkiston valokuvat ovat CC BY-NC-ND 4.0. -lisenssillä (kuvaa saa jakaa, levittää ja näyttää. Nimeä aina aineiston lähde ja tekijä. Älä muokkaa aineistoa.).</p>
<h3>Kohderyhmä:</h3>
<div class="panel-group" id="accordion-kohderyhma" role="tablist" aria-multiselectable="true">
  <div class="panel panel-default">
    <div class="panel-heading" role="tab" id="heading-ylakoulu">
      <h4 class="panel-title">
        <a role="button" data-toggle="collapse" data-parent="#accordion-kohderyhma" href="#ylakoulu">
          Yläkoulu: <small><strong>historia</strong></small>
        </a>
      </h4>
    </div>
    <div id="ylakoulu" class="panel-collapse collapse" role="tabpanel" aria-labelledby="heading-ylakoulu">
      <div class="panel-body">
        <p>Oppiaineiden sisältöalueet:</p>
          <ul class="content-list">
              <li>Historia: S1 Teollisuusyhteiskunnan synty ja kehitys, S2 Ihmiset muuttavat maailmaa, S3 Suomea luodaan, rakennetaan ja puolustetaan, S4 Suurten sotien aika</li>
          </ul>
          <p>Tavoite: Tutustuttaa oppilas sosialismin aatteen levitystyöhön eri tavoin Suomessa. Oppilas harjaantuu tunnistamaan ja tulkitsemaan vaalijulisteissa esiintynyttä propagandaa.</p>
      </div>
    </div>
    </div>
      <div class="panel panel-default">
    <div class="panel-heading" role="tab" id="heading-lukio">
      <h4 class="panel-title">
        <a role="button" data-toggle="collapse" data-parent="#accordion-kohderyhma" href="#lukio">
          Lukio: <small><strong>historia</strong></small>
        </a>
      </h4>
    </div>
    <div id="lukio" class="panel-collapse collapse" role="tabpanel" aria-labelledby="heading-lukio">
      <div class="panel-body">
           <p>Oppiaineet ja kurssit:</p>
          <ul class="content-list">
              <li>Historia HI1 Ihminen ympäristön ja yhteiskuntien muutoksessa, HI3 Itsenäisen Suomen historia</li>
          </ul>
          <p>Tavoite: Tutustuttaa opiskelija sosialismin aatteen levitystyöhön eri tavoin Suomessa. Opiskelija harjaantuu tunnistamaan ja tulkitsemaan vaalijulisteissa esiintynyttä propagandaa.</p>
      </div>
    </div>
  </div>
</div>
<div class="panel panel-default">
  <div class="panel-body">
<h4>Pohdittavaa oppitunneille:</h4>
<ul class="content-list">
    <li>Mikä oli sanansaattajien ja agitaattoreiden tavoite?</li>
    <li>Mitä tarkoittaa propaganda?</li>
    <li>Miksi sosiaalidemokraattinen puolue tavoitteli erityisesti köyhälistön ääniä?</li>
</ul>
</div>
</div>
<ul class="nav nav-tabs help-tabs nav-aineistopaketit">
    <li class="active"><a data-toggle="tab" href="#aineistopaketti">Aineisto</a></li>
    <li><a data-toggle="tab" href="#tehtavaideat">Tehtäväideat</a></li>
</ul>
<div class="tab-content">
     <div id="aineistopaketti" class="tab-pane fade in active">
<?= $this->userlistEmbed(['id' => 706362, 'view' => 'grid', 'title' => false,  'description' => false, 'date' => false, 'allowCopy' => true])?>
</div>
 <div id="tehtavaideat" class="tab-pane fade">
     <p>Tehtäväideat on suunniteltu antamaan ideoita siihen, kuinka voit tarkastella aineistopakettia. Voit lähestyä aihetta valitsemalla tehtävistä yhden tai useamman. Tehtävät voi tehdä yksilö-, pari- tai ryhmätehtävinä. Muokkaa tehtäväideoita eri oppiasteisiin ja oppiaineisiin haluamallasi tavalla.</p>
     <p>Ota yhteyttä Työväen Arkistoon tilataksesi tarkempilaatuisen version aineistoista opetuskäyttöön: info(at)tyark.fi. Tilaus on opettajalle maksuton.</p>
        <div class="panel-group" id="accordion-tehtavaideat" role="tablist" aria-multiselectable="true">
            
  <div class="panel panel-default">
    <div class="panel-heading" role="tab" id="heading-vaalijulisteet">
      <h3 class="panel-title">
        <a class="collapsed" role="button" data-toggle="collapse" data-parent="#accordion-tehtavaideat" href="#vaalijulisteet">
            Vaalijulisteet lähteinä - julisteiden sanoman tulkintaa ja analysointia
        </a>
      </h3>
    </div>
    <div id="vaalijulisteet" class="panel-collapse collapse" role="tabpanel" aria-labelledby="heading-vaalijulisteet">
      <div class="panel-body">
          <h4>Tehtävä 1</h4>
          <p>Tutki <a target="_blank" href="/Record/ta_ah.M011-1459846">”Julistetta”</a>. Sinun ei tarvitse lukea kaikkea julisteen tekstiä, silmäily riittää.</p>
          <ol class="content-list" type="1">
              <li>Mikä aineisto on?</li>
              <li>Miltä vuodelta juliste on?</li>
              <li>Minkä puolueen vaalijuliste on?</li>
              <li>Kenelle juliste on tarkoitettu?</li>
              <li>Ketkä ovat julisteen mukaan riistäjiä?</li>
              <li>Mikä on vaalijulisteen viesti otsikoiden perusteella?</li>
              <li>Yritä lukea vaalijulisteen vuoropuhelua pääotsikon alta. Kerro muutama syy, miksi äänestäjän tulisi äänestää sosialidemokraattista puoluetta.</li>
              <li>Millä keinoilla vaalijuliste pyrkii vaikuttamaan lukijaansa?</li>
           </ol>
          <h4>Tehtävä 2</h4>
          <p>Tutki aineistopaketin <a target="_blank" href="/Record/ta_ah.M011-1459842">”Julistetta”</a>, jossa on pilapiirros.</p>
          <ol class="content-list" type="1">
              <li>Milloin aineisto on painettu?</li>
              <li>Minkä puolueen juliste on?</li>
              <li>Kenelle vaalijuliste on tarkoitettu?</li>
              <li>Mikä on julisteen keskeisin sanoma?</li>
              <li>Millä keinoilla vaalijuliste pyrkii vaikuttamaan lukijaansa?</li>
              <li>Tulkitse pilapiirrosta tarkemmin.
              <br>
              Pilapiirroksen vuorosanat: 1. <i>Kyllä tästä leijonapukuisesta miehestä tulee taas matelija kun pannaan vanhat matelijat sitä hallitsemaan.</i> 2. <i>Kyllähän ne jo osaa madella perustuslaillisetkin mutta jos Suomen kansa näitä haluaa äänestää niin nitsevoo saakoot hallituksen.</i> 3. <i>Me myönnämme teille miehiä sotilaiksi ja miljoonia varustuksiin, se on Suomalaisen puolueen kanta.</i>
              <br>
              <ul class="content-list">
              <li style="list-style-type:lower-roman;">Keitä henkilöitä kuvassa on?</li>
              <li style="list-style-type:lower-roman;">Mitä pilakuvassa tapahtuu?</li>
              <li style="list-style-type:lower-roman;">Pohdi millainen kuva Suomen ja Venäjän poliittisista suhteista välittyy pilakuvan kautta.</li>
              </ul>
              </li>
          </ol>
          <h4>Tehtävä 3</h4>
          <p>Vertaa aineistopaketin vaalijulisteita 2010-luvun vaalijulisteisiin.</p>
          <ol class="content-list" type="1">
              <li>Miten 1900-luvun alun vaalijulisteet pyrkivät vaikuttamaan äänestäjiin?</li>
              <li>Entäpä 2010-luvun vaalijulisteet?</li>
              <li>Mitä eroavaisuuksia huomaat?</li>
              </ol>
              <p>Hakuvinkki: hae hakusanalla ”vaalijuliste 2019”. Löydät esimerkiksi usean sanomalehden tekemiä artikkeleita vuoden 2019 eduskuntavaalien vaalijulisteista.</p>
       </div>
    </div>
  </div>
  
  <div class="panel panel-default">
    <div class="panel-heading" role="tab" id="heading-vastaukset">
      <h3 class="panel-title">
        <a class="collapsed" role="button" data-toggle="collapse" data-parent="#accordion-tehtavaideat" href="#vastaukset">
            Vastaukset
        </a>
      </h3>
    </div>
    <div id="vastaukset" class="panel-collapse collapse" role="tabpanel" aria-labelledby="heading-vastaukset">
      <div class="panel-body">
          <h4>Tehtävä 1</h4>
          <ol class="content-list" type="1">
              <li>1908</li>
              <li>Sosialidemokraattisen puolueen.</li>
              <li>Köyhälistölle, eli työväelle.</li>
              <li>Porvarit.</li>
              <li>Suomen köyhälistön tulisi äänestää sosiaalidemokraatteja, jotta ”kukkarovalta kaatuisi”.</li>
              <li>Tekstissä todetaan, että sosiaalidemokraatit ovat ainoa puolue, joka ajaa köyhälistön etuja. Tekstissä ja koko vaalijulisteessa näkyy ajalla tyypilliset yhteiskunnan ristiriidat ja kahtiajakoisuus porvariston ja työväen keskuudessa. Teksti ottaa kantaa myös pappien etuoikeuksiin. Mikäli köyhälistön jäsen äänestäisi riistäjiä, tulisi heille palkanalennuksia, torpparihäätöjä ja hankaluuksia poliisin kanssa.</li>
              <li>Esimerkiksi: muiden puolueiden tahtotila pitää Suomen olosuhteet sosiaalidemokraattien kannattajille epäedullisina.</li>
              <li>Pyrkii vaikuttamaan perinteisin propagandan keinoin: vetoamalla tunteisiin, vastakkainasettelulla, selkeän yksinkertaisella viestillä ja vastapuolen mustamaalaamisella.</li>
           </ol>
           <h4>Tehtävä 2</h4>
          <ol class="content-list" type="1">
              <li>1907</li>
              <li>Sosialidemokraattisen puolueen.</li>
              <li>Työväen edustajille.</li>
              <li>”Sosiaalidemokraattinen puolue on kansanpuolue”. Vastapuolta syytetään murhaajiksi, ryöstöjen toimeenpanijoiksi ja lupausten pettäjiksi.</li>
              <li>Pyrkii vaikuttamaan perinteisin propagandan keinoin: vetoamalla tunteisiin, vastakkainasettelulla, selkeän yksinkertaisella viestillä ja vastapuolen mustamaalaamisella.</li>
              <li>
            <ul class="content-list">
            <li style="list-style-type:lower-roman;">Kuvassa Venäjän keisari, ministerineuvoston jäseniä ja suomalaisen puolueen kansanedustaja Danielson-Kalmari (ent. johtaja).</li>
              <li style="list-style-type:lower-roman;">Myöntyväisyyslinjaiset ja perustuslailliset ovat keskustelemassa Venäjän keisarin kanssa Suomen uuden hallituksen kokoonpanosta eduskuntavaalien alla.</li>
              <li style="list-style-type:lower-roman;">Pilakuva kuvaa Suomen poliittisten puolueiden olevan Venäjälle myötämielisiä. Niin myötämieliset kuin perustuslailliset. Suomalainen puolue haluaa esittäytyä julkisesti leijonana, Suomen autonomian puolustajana, mutta puolueen johtohahmo Danielson-Kalmari onkin polvillaan Venäjän keisarin edessä. Suomalainen puolue oli myöntyvyyslinjan puolue.</li>
           </ul>
           </li>
           
           </ol>
       </div>
    </div>
  </div>
  
  
    </div>
  </div>
</div>
<!-- END of: national -  content/sosialismi_fi.phtml -->