<!-- START of: custom - content/suojelukuntatoiminta-suomessa_sv.phtml -->
<?php $this->headTitle($this->translate('Skyddskårernas verksamhet i Finland'));?>
<?php if ($this->resolver('luokkahuoneBegin_fi.phtml')): ?>
  <?=$this->render('luokkahuoneBegin_fi.phtml')?>
<?php endif; ?>

<button class="goBack" onclick="goBack()"><i class="fa fa-arrow-left" aria-hidden="true"></i> <?=$this->transEsc('navigate_back') ?></button>

<h2>Skyddskårernas verksamhet i Finland</h2>
<p><strong>Materialet har sammanställts av:</strong> Svenska litteratursällskapet i Finland (SLS)
</p>
<p>Svenska Litteratursällskapet i Finland har sammanställt detta material, som på ett mångsidigt sätt belyser skyddskårernas verksamhet på olika håll i Finland mellan världskrigen.
</p>
<h3>Målgrupp:</h3>
<div class="panel-group" id="accordion-kohderyhma" role="tablist" aria-multiselectable="true">
  <div class="panel panel-default">
    <div class="panel-heading" role="tab" id="heading-ylakoulu">
      <h4 class="panel-title">
        <a role="button" data-toggle="collapse" data-parent="#accordion-kohderyhma" href="#ylakoulu">
          Högstadier: <small><strong>historia</strong></small>
        </a>
      </h4>
    </div>
    <div id="ylakoulu" class="panel-collapse collapse" role="tabpanel" aria-labelledby="heading-ylakoulu">
      <div class="panel-body">
        <p>Läroämnens innehållsområden:</p>
        <ul class="content-list">
          <li>Historia: I2 Människor förändrar världen, I3 Finland skapas, byggs och försvaras
          </li>
        </ul>
        <p>Mål: att med hjälp av foton få en bild av skyddskårernas verksamhet i Finland.
        </p>
      </div>
    </div>
  </div>
  <div class="panel panel-default">
    <div class="panel-heading" role="tab" id="heading-lukio">
      <h4 class="panel-title">
        <a role="button" data-toggle="collapse" data-parent="#accordion-kohderyhma" href="#lukio">
          Gymnasier: <small><strong>historia</strong></small>
        </a>
      </h4>
    </div>
    <div id="lukio" class="panel-collapse collapse" role="tabpanel" aria-labelledby="heading-lukio">
      <div class="panel-body">
        <p>Läroämnens kurser:</p>
        <ul class="content-list">
          <li>Historia: HI2 Internationella relationer, HI3 Det självständiga Finlands historia
          </li>
        </ul>
        <p>Mål: att med hjälp av foton få en bild av skyddskårernas verksamhet i Finland.
        </p>
      </div>
    </div>
  </div>
</div>

<ul class="nav nav-tabs help-tabs nav-aineistopaketit">
  <li class="active"><a data-toggle="tab" href="#aineistopaketti">Material</a>
  </li>
  <li><a data-toggle="tab" href="#tehtavaideat">Uppgiftsidéer</a>
  </li>
</ul>
<div class="tab-content">
  <div id="aineistopaketti" class="tab-pane fade in active">
    <?=$this->userlistEmbed(['id' => 64, 'view' => 'grid', 'title' => false, 'description' => true, 'date' => false, 'allowCopy' => true])?>
  </div>
  <div id="tehtavaideat" class="tab-pane fade">
    <p>Uppgiftsidéerna ger tips för hur du kan studera materialpaketet. Du kan granska ett tema genom att välja en eller flera uppgifter. Uppgifterna kan utföras individuellt, i par eller grupp. Omarbeta uppgiftsidéerna för olika utbildningsstadier och läroämnen på önskat sätt.
    </p>
    <div class="panel-group" id="accordion-tehtavaideat" role="tablist" aria-multiselectable="true">
      <div class="panel panel-default">
        <div class="panel-heading" role="tab" id="heading-valokuvat">
          <h3 class="panel-title">
            <a class="collapsed" role="button" data-toggle="collapse" data-parent="#accordion-tehtavaideat" href="#valokuvat">
              Fotografier som källa - analys och tolkning av bilder
            </a>
          </h3>
        </div>
        <div id="valokuvat" class="panel-collapse collapse" role="tabpanel" aria-labelledby="heading-valokuvat">
          <div class="panel-body">
            <h4>Uppgift 1</h4>
            <p>Analysera fotona i materialet.
            </p>
            <ol class="content-list" type="1">
              <li>Vem deltog i skyddskårernas verksamhet?
              </li>
              <li> Titta på fotot <a target="_blank" href="/Record/sls.SLS+1555_SLS+1555_1628">"Mat serveras åt militärgossarna. (1920)"</a>. Vilken var kvinnornas roll i skyddskårernas verksamhet enligt fotot?
              </li>
              <li>Kvinnorna på fotot <a target="_blank" href="/Record/sls.SLS+1555_SLS+1555_1628">"Mat serveras åt militärgossarna. (1920)"</a> hörde sannolikt till organisationen Lotta Svärd. Utred med hjälp av webben vad organisationen Lotta Svärd var och övriga uppgifter lottorna hade.
              </li>
            </ol>
            <h4>Uppgift 2</h4>
            <p>Titta på fotot <a target="_blank" href="/Record/sls.%25C3%2596TA+311_%25C3%25B6ta+311+foto+61">"Ateljéfotografi av militärklädd ung man som ..."</a> och svara på frågorna nedan.
            </p>
            <ol class="content-list" type="1">
              <li>Varför har ynglingen låtit fotografera sig i stridsutrustning på en fotoateljé.
              </li>
              <li>Ta del av ytterligare information i materialet. Utred var i Finland fotot sannolikt är taget. Hur kom du fram till det?
              </li>
              <li>Tidsperioden för materialet är 1910–1942. Hur kan man veta att fotot sannolikt inte är taget före 1917?
              </li>
            </ol>
            <h4>Uppgift 3</h4>
            <ol class="content-list" type="1">
              <li>Hurdana fritidsintressen hittar du på fotona?
              </li>
              <li>Varför hade idrott en så stor betydelse för finländarna mellan världskrigen?
              </li>
            </ol>          
            <h4>Uppgift 4</h4>
            <p>Titta på fotot <a target="_blank" href="/Record/sls.SLS+1555_SLS+1555_1638">"Paraden den 13. (1919)"</a>.
            </p>
            <ol class="content-list" type="1">
              <li>Vad sker på fotot?
              </li>
              <li>Vad fäste du först uppmärksamhet vid när du tittade på fotot? Hurdan stämning har fotot? Varför?
              </li>
              <li>Hurdan stämning har fotot?
              </li>
              <li>Varför har fotot tagits? Vad vill man berätta med fotot för betraktaren?
              </li>
            </ol>
            <h4>Uppgift 5</h4>
            <p>Titta på fotona av krigsövningar i materialet. Titta åtminstone på fotona <a target="_blank" href="/Record/sls.SLS+1555_SLS+1555_804">"Unga skyddskårister i ställning. (1920)"</a> och  <a target="_blank" href="/Record/sls.SLS+1555_SLS+1555_804">"Målskjutning. (1920)"</a>. Läs bildtexterna och svara på frågorna.
            </p>
            <ol class="content-list" type="1">
              <li>Vad sker på fotona?
              </li>
              <li>När och var är fotona tagna?
              </li>
              <li>Hurdan stämning har fotona?
              </li>
              <li>Varför har fotona tagits? Vad vill man berätta med fotona?
              </li>
              <li>För vem är fotona avsedda?
              </li>
            </ol>
          </div>
        </div>
      </div>
      <div class="panel panel-default">
        <div class="panel-heading" role="tab" id="heading-vastaukset">
          <h3 class="panel-title">
            <a class="collapsed" role="button" data-toggle="collapse" data-parent="#accordion-tehtavaideat" href="#vastaukset">
              Svar
            </a>
          </h3>
        </div>
        <div id="vastaukset" class="panel-collapse collapse" role="tabpanel" aria-labelledby="heading-vastaukset">
          <div class="panel-body">
            <h4>Uppgift 2</h4>
            <ol class="content-list" type="1" start="2">
              <li>Fotot är sannolikt taget i Österbotten. Materialet tillhör familjen Sorvaris arkiv, och samlingen förvaras vid SLS. Familjen Sorvari bodde i Malax, Vasa och Ilmola i Österbotten. Dessutom finns material i "Traditions- och lokalhistoriska samlingen i Österbotten".
              </li>
              <li>Skyddskårsverksamheten blev mer aktiv i Finland först efter ryska revolutionen.
              </li>
            </ol>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>
<!-- END of: custom - content/suojelukuntatoiminta-suomessa_sv.phtml -->
