<!-- START of: custom - content/suomi-vanhoissa-kartoissa_sv.phtml -->
<?php $this->headTitle('Finland på gamla kartor');?>
<?php if ($this->resolver('luokkahuoneBegin_fi.phtml')): ?>
  <?=$this->render('luokkahuoneBegin_fi.phtml')?>
<?php endif; ?>

<button class="goBack" onclick="goBack()"><i class="fa fa-arrow-left" aria-hidden="true"></i> <?=$this->transEsc('navigate_back') ?></button>

<h2>Finland på gamla kartor</h2>
<p><strong>Materialet har sammanställts av</strong> Nationalbiblioteket
</p>
<p>I slutet av medeltiden dök Finland upp på kartor över Europa samtidigt som de övriga nordiska länderna. Finland var då en del av Kungariket Sverige. På kartor användes det latinska namnet för Finland, Finlandia.
</p>
<p>De äldsta kartorna över norra Europa utgavs som delar i stora kartböcker, dvs. atlaser, under de sista årtiondena på 1400-talet. Uppfattningen om den nordiska geografin var mycket inexakt i dem.
</p>
<p>På 1530-talet ritade den svenske lärde kyrkomannen Olaus Magnus (1490–1557) en bättre karta över Norden. Den är känd med namnet Carta marina. Carta marina var ett stort framsteg i utvecklingen av kartor över Finland. Olaus Magnus användes ända till början av 1600-talet då Anders Bures (1571–1646) mer exakta karta ersatte den. Bures karta användes i otaliga publikationer fram till 1700-talet.
</p>
<p>Detta materialpaket som sammanställts av Nationalbiblioteket visar med hjälp av åtta kartor hur Finland har sett ut på kartor sedan slutet av 1400-talet. Alla kartor nedan är digitaliserade versioner från Nationalbibliotekets (Helsingfors) samlingar.
</p>
<h3>Målgrupp:</h3>
<div class="panel-group" id="accordion-kohderyhma" role="tablist" aria-multiselectable="true">
  <div class="panel panel-default">
    <div class="panel-heading" role="tab" id="heading-alakoulu">
      <h4 class="panel-title">
        <a role="button" data-toggle="collapse" data-parent="#accordion-kohderyhma" href="#alakoulu">
          Lågstadier: <small><strong>bildkonst, historia, omgivningslära</strong></small>
        </a>
      </h4>
    </div>
    <div id="alakoulu" class="panel-collapse collapse" role="tabpanel" aria-labelledby="heading-alakoulu">
      <div class="panel-body">
        <p>Läroämnens innehållsområden:</p>
        <ul class="content-list">
          <li>Bildkonst: I1 Egna bildkulturer, I2 Bildkulturer i omgivningen
          </li>
          <li>Historia: I4 Nya tiden - ett brytningsskede
          </li>
          <li>Omgivningslära: I3 På upptäcktsfärd i en pluralistisk värld
          </li>
        </ul>
        <p>Mål: Att göra eleverna bekanta med historiska kartor. Materialet hjälper eleverna att lägga märke till förändringar i den europeiska vetenskapen och världsbilden. Genomförande av helhetsskapande undervisning.
        </p>
      </div>
    </div>
  </div>
  <div class="panel panel-default">
    <div class="panel-heading" role="tab" id="heading-lukio">
      <h4 class="panel-title">
        <a role="button" data-toggle="collapse" data-parent="#accordion-kohderyhma" href="#lukio">
          Gymnasier: <small><strong>historia</strong></small>
        </a>
      </h4>
    </div>
    <div id="lukio" class="panel-collapse collapse" role="tabpanel" aria-labelledby="heading-lukio">
      <div class="panel-body">
        <p>Läroämnens kurser:</p>
        <ul class="content-list">
          <li>HI1 Människan i en föränderlig omvärld, HI4 En europeisk världsbild växer fram, HI5 Sveriges östra rikshalva blir Finland
          </li>
        </ul>
        <p>Mål: Studerande lär sig använda kartor som historiska källor. Materialet hjälper studerandena att bland annat bedöma förändringar i den europeiska vetenskapen och världsbilden.
        </p>
      </div>
    </div>
  </div>
</div>

<ul class="nav nav-tabs help-tabs nav-aineistopaketit">
  <li class="active"><a data-toggle="tab" href="#aineistopaketti">Material</a>
  </li>
  <li><a data-toggle="tab" href="#tehtavaideat">Uppgiftsidéer</a>
  </li>
</ul>
<div class="tab-content">
  <div id="aineistopaketti" class="tab-pane fade in active">
    <?=$this->userlistEmbed(['id' => 63, 'view' => 'grid', 'title' => false, 'description' => false, 'date' => false, 'allowCopy' => true])?>
  </div>
  <div id="tehtavaideat" class="tab-pane fade">
    <p>Uppgiftsidéerna ger tips för hur du kan studera materialpaketet. Du kan granska ett tema genom att välja en eller flera uppgifter. Uppgifterna kan utföras individuellt, i par eller grupp. Omarbeta uppgiftsidéerna för olika utbildningsstadier och läroämnen på önskat sätt.
    </p>
    <h4>Lågstadier</h4>
    <div class="panel-group" id="accordion-tehtavaideat" role="tablist" aria-multiselectable="true">
      <div class="panel panel-default">
        <div class="panel-heading" role="tab" id="heading-1500">
          <h3 class="panel-title">
            <a class="collapsed" role="button" data-toggle="collapse" data-parent="#accordion-tehtavaideat" href="#1500">
              Finland nämns! Undersök hur Norden och i synnerhet Finland har avbildats på kartan från 1500-talet.
            </a>
          </h3>
        </div>
        <div id="1500" class="panel-collapse collapse" role="tabpanel" aria-labelledby="heading-1500">
          <div class="panel-body">
            <p><strong>Bakgrundsinformation:</strong> I början av 1500-talet ritade den svenske lärde kyrkomannen Olaus Magnus (f. 1490 – d. 1557) en karta över Norden som är känd med namnet Carta Marina. Kartan är den första kartan över Norden med ortnamn och beskrivningar av platser. Att rita kartor tog tid och krävde exakthet – Olaus Magnus använde hela 12 år på sin karta. Carta Marina var mycket mer exakt än de tidigare kartorna och var rikligt illustrerad. Carta Marina var också en stor karta med nio delar. Utvecklad var kartans dimensioner hela 170 x 125 cm. Olaus Magnus karta användes i cirka hundra år till början av 1600-talet.
            </p>
            <p>I denna uppgift undersöker vi <a target="_blank" href="/Record/doria.10024_147788">Carta marina från 1572</a>. Kartan är visuellt sett mycket exakt, och det är roligt att studera den tillsammans med eleverna. Carta Marina lämpar sig utmärkt för till exempel:
            </p>
            <p><strong>Undervisning i historia</strong>: Kan användas som stöd i undervisningen i nya tiden. Materialet kan användas för att illustrera hur människor har föreställt sig världen och hur detta återspeglas i kartor.
            </p>
            <p><strong>Undervisning i miljölära</strong>: Carta Marina kan användas i miljölära när man går igenom moderna kartor över Finland och Europa. Man kan jämföra kartorna och tillsammans hur och varför de skiljer sig från varandra. Med hjälp av materialet kan man diskutera principerna för kartografi förr och i dag.
            </p>
            <p>Frågor på lektioner i historia och/eller miljölära:
            </p>
            <ul class="content-list">
              <li>Hittar du Finland på kartan? Och Sverige? Kan du berätta var Island finns?
              </li>
              <li>Vilka bekanta ord/namn hittar du på kartan? Vilken nutida stad kan de syfta på?
              </li>
              <li>Tycker du att kartan är tydlig? Diskutera varför kartan har ritats.
              </li>
              <li>Vilket språk används på kartan? Varför?
              </li>
              <li>Det tog tolv år för Olaus Magnus att rita kartan i Venedig. Vilka problem kan ha förekommit när man ritade kartor på 1500-talet?
              </li>
              <li>På kartan finns flera illustrationer. Studera dem. Diskutera varför det finns illustrationer på kartan från början av den nya tiden.
              </li>
              <li>Vilka djur hittar du på kartan?
              </li>
              <li>Vilka fordon hittar du på kartan?
              </li>
              <li>Vad berättar illustrationerna på kartan om livet på 1500-talet?
              </li>
              <li>Jämför kartan från 1572 med en modern karta. Hur skiljer sig kartorna från varandra? Och finns det några likheter mellan dem? Kom med några exempel.
              </li>
              <li>Diskutera varför Finland inte ser likadant ut på en karta från 1500-talet som på en modern karta.
              </li>
            </ul>
            <br>
            <p><strong>Undervisning i bildkonst</strong>:
            </p>
            <p>Uppgiftidé 1: Uppgiften går ut på att rita en karta över hemorten. Använd Carta Marina som inspirationskälla. Uppgiften kan utföras individuellt, i par eller grupp.
            </p>
            <p>Uppgiftidé 2: Eleverna ritar en ny karta över Norden i samma stil som Carta Marina. Kartan illustreras med bilder av samtida människors liv, saker, fordon, djur och natur. Uppgiften kan utföras individuellt, i par eller grupp.
            </p>
            <p>Diskussionsämnen relaterade till bildkonstuppgiften:
            </p>
            <ul class="content-list">
              <li>Vilka faktorer påverkar ritandet av kartor?
              </li>
              <li>Hur var det att rita en karta?
              </li>
              <li>Vilka slutsatser kan man dra av kartritningsuppgiften?
              </li>
            </ul>
            <br>
            <p>Obs! Du kan också studera en version av <a target="_blank" href="https://upload.wikimedia.org/wikipedia/commons/e/ea/Carta_Marina.jpeg">kartan i färg</a> på Wikipedia.
            </p>
          </div>
        </div>
      </div>
      <h4>Gymnasier</h4>
      <div class="panel panel-default">
        <div class="panel-heading" role="tab" id="heading-1493">
          <h3 class="panel-title">
            <a class="collapsed" role="button" data-toggle="collapse" data-parent="#accordion-tehtavaideat" href="#1493">
              Karta från 1493 (Europa centralis et septentrionalis)
            </a>
          </h3>
        </div>
        <div id="1493" class="panel-collapse collapse" role="tabpanel" aria-labelledby="heading-1493">
          <div class="panel-body">
            <p>Karta: <a target="_blank" href="/Record/doria.10024_123053#image">från 1493 (Europa centralis et septentrionalis)</a>
            </p>
            <h6>Uppgift</h6>
            <ol class="content-list">
              <li>Placera ut följande länder och städer på kartan över Europa och Norden från 1493:
                <ul class="content-list">
                  <li>Finland</li>
                  <li>Sverige</li>
                  <li>Danmark</li>
                  <li>Island</li>
                  <li>Grönland</li>
                  <li>Paris</li>
                  <li>London</li>
                  <li>Moskva</li>
                  <li>München</li>
                  <li>Basel</li>
                  <li>Budapest</li>
                  <li>Marseille</li>
                </ul>
              </li>
              <li>Ta reda på i vilket verk kartan ursprungligen har publicerats. Ett hurdant verk var det fråga om?
              </li>
            </ol>
          </div>
        </div>
      </div>
      <div class="panel panel-default">
        <div class="panel-heading" role="tab" id="heading-1572">
          <h3 class="panel-title">
            <a class="collapsed" role="button" data-toggle="collapse" data-parent="#accordion-tehtavaideat" href="#1572">
              Carta marina från 1572 
            </a>
          </h3>
        </div>
        <div id="1572" class="panel-collapse collapse" role="tabpanel" aria-labelledby="heading-1572">
          <div class="panel-body">
            <p>Karta: <a target="_blank" href="/Record/doria.10024_123053#image">Carta marina från 1572</a>
            </p>
            <h6>Uppgift 1</h6>
            <p>Kartans resolution är mycket stor och dess visuella språk är mycket rikt. Planera och förverkliga på basis av kartan ett eget konstnärligt projekt.
            </p>
            <h6>Uppgift 2</h6>
            <ol class="content-list">
              <li>Koppla så många orter som möjligt på kartan med de nuvarande ortnamnen (t.ex. Hange = Hangö).
              </li>
              <li>Fundera på följande frågor då du/ni granskat ortsnamnen:
                <ul class="content-list">
                  <li>På vilket sätt och på vilka ställen är kartan relativt exakt?
                  </li>
                  <li>På vilka ställen är den inexakt?
                  </li>
                  <li>Vad beror detta på? Och varför är Finland en avlång udde som sträcker sig mot sydväst?
                  </li>
                </ul>
              </li>
            </ol>
          </div>
        </div>
      </div>
      <div class="panel panel-default">
        <div class="panel-heading" role="tab" id="heading-1635">
          <h3 class="panel-title">
            <a class="collapsed" role="button" data-toggle="collapse" data-parent="#accordion-tehtavaideat" href="#1635">
              Karta från 1635
            </a>
          </h3>
        </div>
        <div id="1635" class="panel-collapse collapse" role="tabpanel" aria-labelledby="heading-1635">
          <div class="panel-body">
            <p>Karta: <a target="_blank" href="/Record/doria.10024_123053#image">från 1635</a>
            </p>
            <h6>Uppgift</h6>
            <p>Kartan från år 1635 är framställd av Gerardus Mercator. Hans rykte baserar sig på den så kallade Mercator-projektionen. Sök mer information på webben om projektionen och svara på frågorna nedan.
            </p>
            <ol class="content-list">
              <li>Vad är projektion?
              </li>
              <li>Och var används Mercator-projektion i dag?
              </li>
              <li>Vilka andra typer av projektioner finns det?
              </li>
            </ol>
          </div>
        </div>
      </div>
      <div class="panel panel-default">
        <div class="panel-heading" role="tab" id="heading-1700">
          <h3 class="panel-title">
            <a class="collapsed" role="button" data-toggle="collapse" data-parent="#accordion-tehtavaideat" href="#1700">
              Karta från 1721 och kartor från 1743-1809
            </a>
          </h3>
        </div>
        <div id="1700" class="panel-collapse collapse" role="tabpanel" aria-labelledby="heading-1700">
          <div class="panel-body">
            <p>Kartor:
            </p>
            <ul class="content-list">
              <li><a target="_blank" href="/Record/doria.10024_146925#image">karta från 1721</a>
              </li>
              <li><a target="_blank" href="/Record/doria.10024_123031#image">kartor från 1743-1809</a>
              </li>
            </ul>
            <h6>Uppgift</h6>
            <ol class="content-list">
              <li>Jämför kartorna. Hur avviker svenska rikets gränser från varandra på dem? Till vad anknyter detta, och vad inträffade 1721?
              </li>
              <li>Den senare kartan saknar tryckår. Hur kan vi dock veta att den tryckts mellan 1743 och 1809?
              </li>
            </ol>
          </div>
        </div>
      </div>
      <div class="panel panel-default">
        <div class="panel-heading" role="tab" id="heading-1820">
          <h3 class="panel-title">
            <a class="collapsed" role="button" data-toggle="collapse" data-parent="#accordion-tehtavaideat" href="#1820">
              Karta från 1820
            </a>
          </h3>
        </div>
        <div id="1820" class="panel-collapse collapse" role="tabpanel" aria-labelledby="heading-1820">
          <div class="panel-body">
            <p>Karta: <a target="_blank" href="/Record/doria.10024_63988">från 1820</a>
            </p>
            <h6>Uppgift 1</h6>
            <p>Finland syns på kartan som en del av Kejsardömet Ryssland. Varför är nuvarande Finland på kartan indelad i två områden (de gula gränserna)?
            </p>
            <h6>Uppgift 2</h6>
            <p>Kartan är tryckt i Weimar. Största delen av kartorna i denna Finna-helhet har tryckts i livliga handelsstäder, såsom Amsterdam och Paris. Weimar är däremot en liten tysk stad i inlandet. Varför trycktes där dock kartor på 1820-talet?
            </p>
          </div>
        </div>
      </div>
      <div class="panel panel-default">
        <div class="panel-heading" role="tab" id="heading-vastaukset">
          <h3 class="panel-title">
            <a class="collapsed" role="button" data-toggle="collapse" data-parent="#accordion-tehtavaideat" href="#vastaukset">
              Svar
            </a>
          </h3>
        </div>
        <div id="vastaukset" class="panel-collapse collapse" role="tabpanel" aria-labelledby="heading-vastaukset">
          <div class="panel-body">
            <p><strong>Carta marina från 1572</strong>
            </p>
            <p>Upgift 2
            </p>
            <ol class="content-list" start="2">
              <li>Idéen är att observera att kartan är relativt exakt vid kusten, eftersom orterna för det mesta är rätt utplacerade i förhållande till varandra. Mot inlandet blir kartan hela tiden allt mer fantasifull. Detta tyder på att den finska kusten var en väl känd trakt redan på medeltiden. Den var en fast del av svenska riket, och dess handelskontakter med Baltikum, Ryssland och Tyskland var livliga. På medeltiden och 1500-talet var havet ett förenande element medan långa landavstånd utgjorde ett isolerande element.
              </li>
            </ol>
            <p>Finlands form på kartan beror på detta. Kusten var känd, och man kunde relatera platserna till varandra. Därför ville man använda mer utrymme för att avbilda den än för att avbilda det okända inlandet.
            </p>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>
<!-- END of: custom - content/suomi-vanhoissa-kartoissa_sv.phtml -->
