<!-- START of: custom - content/talvisota_fi.phtml -->
<?php $this->headTitle($this->translate('Puolustusvoimien talvisodan valokuva-aineistoa'));?>
<?php if ($this->resolver('luokkahuoneBegin_fi.phtml')): ?>
  <?=$this->render('luokkahuoneBegin_fi.phtml')?>
<?php endif; ?>

<button class="goBack" onclick="goBack()"><i class="fa fa-arrow-left" aria-hidden="true"></i> <?=$this->transEsc('navigate_back') ?></button>

<h2>Puolustusvoimien talvisodan valokuva-aineistoa</h2>
<p><strong>Aineistopaketin koonnut:</strong> Sotamuseo
</p>
<p>Sotahistorian opetukseen tarkoitettu aineisto on kerätty Sotamuseon SA-kuva-arkistosta. Arkisto käsittää n. 160 000 sodan ajan Puolustusvoimien rintamavalokuvaajien (TK-kuvaajat) ottamaa valokuvaa vuosien 1939–1945 välisenä aikana. Aineisto on jaettu kolmeksi aineistopaketiksi: talvisota, jatkosota ja Lapin sota. Tähän aineistopakettiin on koottu kuvia talvisodasta alkaen syksyn 1939 poliittisesta tilanteesta päättyen rauhaan vuonna 1940.
</p>
<p>Talvisodan aikana kuvaustoimintaa ei ehditty organisoimaan tiedotuskomppanioissa (TK) yhtä järjestelmälliseksi kuin jatkosodan aikana. Tästä johtuen kuvista uupuu kuvatekstejä ja kuvaaja- ja paikkakuntatiedot ovat toisinaan vaillinaisia. Kuvaamisella oli kuitenkin selkeä tehtävä: niiden kautta välitettiin tunnelmia niin koti- kuin sotarintamalle aikakausi- ja sanomalehtijulkaisujen kautta.
</p>
<p>Kuvia käytettäessä on hyvä pitää mielessä aineiston alkuperäinen tarkoitus. Kuvien kuvatekstit ovat valokuvaajien kirjoittamia alkuperäisiä selosteita ja niitä tulisi lukea ajan hengen tuotoksina. Teksteissä käytetään varsin värikästä kieltä ja joukossa voi olla myös halventavia sanavalintoja. Niin ikään on hyvä pitää mielessä se, että osa kuvista on lavastettu tai muutoin aseteltuja.
</p>
<p>Kuva-aineistoa voi käyttää historian tapahtumien visualisointiin ja tuon ajanjakson elämään tutustumiseen. Valokuvat ovat myös oiva aineisto medialukutaidon opetukseen. Propagandatuotteina ne toimivat hyvänä esimerkkinä siitä, miten kuvallisella viestinnällä voidaan vaikuttaa mielialoihin ja mielipiteisiin.
</p>
<h3>Kohderyhmä:</h3>
<div class="panel-group" id="accordion-kohderyhma" role="tablist" aria-multiselectable="true">
  <div class="panel panel-default">
    <div class="panel-heading" role="tab" id="heading-ylakoulu">
      <h4 class="panel-title">
        <a role="button" data-toggle="collapse" data-parent="#accordion-kohderyhma" href="#ylakoulu">
          Yläkoulu: <small><strong>historia</strong></small>
        </a>
      </h4>
    </div>
    <div id="ylakoulu" class="panel-collapse collapse" role="tabpanel" aria-labelledby="heading-ylakoulu">
      <div class="panel-body">
         <p>Oppiaineiden sisältöalueet:</p>
          <ul class="content-list">
              <li>Historia: S3 Suomea luodaan, rakennetaan ja puolustetaan, S4 Suurten sotien aika</li>
        </ul>
        <p>Tavoite: Kuva-aineistoa voi käyttää historian tapahtumien visualisointiin ja tuon ajanjakson elämään tutustumiseen. Valokuvat ovat myös oiva aineisto medialukutaidon opetukseen. Propagandatuotteina ne toimivat hyvänä esimerkkinä siitä, miten kuvallisella viestinnällä voidaan vaikuttaa mielialoihin ja mielipiteisiin.
        </p>
      </div>
    </div>
  </div>
  <div class="panel panel-default">
    <div class="panel-heading" role="tab" id="heading-lukio">
      <h4 class="panel-title">
        <a role="button" data-toggle="collapse" data-parent="#accordion-kohderyhma" href="#lukio">
          Lukio: <small><strong>historia</strong></small>
        </a>
      </h4>
    </div>
    <div id="lukio" class="panel-collapse collapse" role="tabpanel" aria-labelledby="heading-lukio">
      <div class="panel-body">
        <p>Oppiaineet ja kurssit:</p>
          <ul class="content-list">
              <li>Historia: HI3 Itsenäisen Suomen historia</li>
           </ul>
        <p>Tavoite: Kuva-aineistoa voi käyttää historian tapahtumien visualisointiin ja tuon ajanjakson elämään tutustumiseen. Valokuvat ovat myös oiva aineisto medialukutaidon opetukseen. Propagandatuotteina ne toimivat hyvänä esimerkkinä siitä, miten kuvallisella viestinnällä voidaan vaikuttaa mielialoihin ja mielipiteisiin.
        </p>
      </div>
    </div>
  </div>
</div>

<ul class="nav nav-tabs help-tabs nav-aineistopaketit">
  <li class="active"><a data-toggle="tab" href="#aineistopaketti">Aineisto</a>
  </li>
  <li><a data-toggle="tab" href="#tehtavaideat">Tehtäväideat</a>
  </li>
</ul>
<div class="tab-content">
  <div id="aineistopaketti" class="tab-pane fade in active">
    <?=$this->userlistEmbed(['id' => 66, 'view' => 'grid', 'title' => false, 'description' => false, 'date' => false, 'allowCopy' => true])?>
    <div class="panel panel-default">
      <div class="panel-body">
        <h4>Vinkkejä vastaavan aineiston hakemiseen</h4>
        <p>Kaipaatko lisää aineistoa talvisodan käsittelyyn Sotamuseon aineistoista? Etsi vastaavaa aineistoa <a href="/">Finna.fi</a>-hakupalvelusta seuraavin keinoin:
        </p>
        <p><strong>Hakusana:</strong> Hae aineistopaketin aineistojen otsikoista löytyvillä hakusanoilla, esimerkiksi "ilmatorjunta" tai "lotta OR lotat".
        </p>
        <p><strong>Organisaatio:</strong> Valitse organisaatioksi Sotamuseo.
        </p>
        <p><strong>Parhaat rajaimet:</strong> Rajaa tuloksia valitsemalla <strong>Verkossa saatavilla</strong> olevaa aineistoa. Rajaa aineisto koskemaan talvisotaa valitsemalla <strong>Valmistusvuosi</strong>-valikosta itseäsi kiinnostavat vuodet.
        </p>
        <p><strong>Lisätietoja aineistoista:</strong> Mikäli kaipaat lisätietoja tietystä aineistosta, löydät sen <a href="http://sa-kuva.fi">www.sa-kuva.fi</a> -palvelusta.
        </p>
      </div>
    </div>
  </div>
  <div id="tehtavaideat" class="tab-pane fade">
    <p>Tehtäväideat on suunniteltu antamaan ideoita siihen, kuinka voit tarkastella aineistopakettia. Voit lähestyä aihetta valitsemalla tehtävistä yhden tai useamman. Tehtävät voi tehdä yksilö-, pari- tai ryhmätehtävinä. Muokkaa tehtäväideoita eri oppiasteisiin ja oppiaineisiin haluamallasi tavalla.
    </p>
    <div class="panel-group" id="accordion-tehtavaideat" role="tablist" aria-multiselectable="true">
      <div class="panel panel-default">
        <div class="panel-heading" role="tab" id="heading-aika-ennen">
          <h3 class="panel-title">
            <a class="collapsed" role="button" data-toggle="collapse" data-parent="#accordion-tehtavaideat" href="#aika-ennen">
              Aika ennen talvisodan virallista syttymistä
            </a>
          </h3>
        </div>
        <div id="aika-ennen" class="panel-collapse collapse" role="tabpanel" aria-labelledby="heading-aika-ennen">
          <div class="panel-body">
            <h4>Tehtävä 1</h4>
            <p>Tutustu <a target="_blank" href="/List/703629?limit=50&view=grid&filter%5B%5D=lists%3A%22703629%22">aineistopaketin valokuviin</a> ajalta ennen talvisodan syttymistä ja vastaa alla oleviin kysymyksiin.</p>
            <ol class="content-list" type="1">
              <li>Miten Suomessa varauduttiin mahdolliseen talvisotaan? Ketkä osallistuivat?
              </li>
              <li>Millainen tunnelma valokuvista välittyy? Mitä valokuvien henkilöiden ilmeet kertovat?
              </li>
              <li>Arvioi kuvien luotettavuutta historiallisena lähteenä.
              </li>
            </ol>
            <h4>Tehtävä 2</h4>
            <p>Tarkastele lähemmin valokuvia <a target="_blank" href="/Record/sa-kuva.sa-kuva-113071">"Sormuskeräys"</a> ja <a target="_blank" href="/Record/sa-kuva.sa-kuva-111824">"Ravintola Prestossa kudotaan sukkia ennen talvisotaa."</a>.
            </p>
            <ol class="content-list" type="1">
              <li>Mitä kuvissa tapahtuu?
              </li>
              <li>Miten kuvat liittyvät aikaan hieman ennen talvisotaa?
              </li>
              <li>Millainen tunnelma valokuvista välittyy? Mitä valokuvan henkilöiden ilmeet kertovat?
              </li>
              <li>Arvioi kuvien luotettavuutta historiallisena lähteenä.
            <ul class="content-list">
                <li>Mikä taho valokuvat on ottanut?</li>
                <li>Pohdi, miksi valokuvat on otettu. Perustele.</li>
                <li>Mitä kuvissa näytetään ja mitä niissä EI näytetä?</li>
              </ul>
              </li>
            </ol>
          </div>
        </div>
      </div>
      <div class="panel panel-default">
        <div class="panel-heading" role="tab" id="heading-talvisodan-tapahtumia">
          <h3 class="panel-title">
            <a class="collapsed" role="button" data-toggle="collapse" data-parent="#accordion-tehtavaideat" href="#talvisodan-tapahtumia">
              Talvisodan tapahtumia
            </a>
          </h3>
        </div>
        <div id="talvisodan-tapahtumia" class="panel-collapse collapse" role="tabpanel" aria-labelledby="heading-talvisodan-tapahtumia">
          <div class="panel-body">
            <h4>Tehtävä 1</h4>
            <p>Tarkastele aineistopaketin valokuvia <a target="_blank" href="/Record/sa-kuva.sa-kuva-105711">"Sotasaalista ja kaatuneita Raatteen tiellä."</a>, <a target="_blank" href="/Record/sa-kuva.sa-kuva-105275">"Vallattu panssariauto Tolvajärven rintamalta."</a> ja <a target="_blank" href="/Record/sa-kuva.sa-kuva-112876">"Sotasaaliiksi saatuja vihollisen suksia Raatteen tiellä"</a>.
            </p>
            <ol class="content-list" type="1">
              <li>Mitä kuvissa tapahtuu?
              </li>
              <li>Miten kuvat eroavat toisistaan? Perustele.
              </li>
              <li>Mitä kuvat kertovat suomalaisten toiminnasta talvisodassa?
              </li>
              <li>Arvioi kuvan luotettavuutta historiallisena lähteenä.
              <ul class="content-list">
                  <li>Mikä taho valokuvat on ottanut?</li>
                  <li>Pohdi, miksi valokuvat on otettu. Perustele.</li>
                  <li>Mitä kuvissa näytetään ja mitä niissä EI näytetä?</li>
              </ul>
              </li>
            </ol>
            <h4>Tehtävä 2</h4>
            <p>Tutustu aineistopaketin <a target="_blank" href="/List/703629?limit=50&view=grid&filter%5B%5D=lists%3A%22703629%22">valokuviin lotista</a>.
            </p>
            <ol class="content-list" type="1">
              <li>Keitä lotat olivat? Käytä apuna oppikirjaasi tai verkkoa.
              </li>
              <li>Millaisia tehtäviä lotilla oli aineistopaketin valokuvien perusteella?
              </li>
              <li>Miksi lotat vastasivat esimerkiksi rintamasotilaiden joulupakettien teosta?
              </li>
            </ol>
          </div>
        </div>
      </div>
      <div class="panel panel-default">
        <div class="panel-heading" role="tab" id="heading-empatian-harjoittelua">
          <h3 class="panel-title">
            <a class="collapsed" role="button" data-toggle="collapse" data-parent="#accordion-tehtavaideat" href="#empatian-harjoittelua">
              Historiallisen empatian harjoittelua
            </a>
          </h3>
        </div>
        <div id="empatian-harjoittelua" class="panel-collapse collapse" role="tabpanel" aria-labelledby="heading-empatian-harjoittelua">
          <div class="panel-body">
            <h4>Tehtävä 1 - Evakkomatka</h4>
            <p>Tarkastele valokuvaa <a target="_blank" href="/Record/sa-kuva.sa-kuva-111155">"Evakuointia Karjalan kannaksella sodan alkupäivinä."</a>. Kuvittele itsesi kuvassa etualalla olevan lapsen asemaan. Kirjoita hänen näkökulmastaan lyhyt päiväkirjamerkintä evakkomatkasta.
            </p>
            <h4>Tehtävä 2 - Helsinkiläisiä pommisuojassa</h4>
            <p>Tarkastele valokuvaa <a target="_blank" href="/Record/sa-kuva.sa-kuva-111015">"Helsinkiläisiä pommisuojassa."</a>. Kuvittele itsesi pommisuojaan valokuvassa olevien henkilöiden kanssa, ja kirjoita twiitti olostasi siellä. Kerro, mitä ajattelet ja tunnet.
            </p>
            <h4>Tehtävä 3 - Tehtävä lukiolaisille</h4>
            <p>Etsi tietoa ja tutustu Raatteen tien tapahtumiin talvisodan aikana. Tutki tämän jälkeen <a target="_blank" href="/Record/sa-kuva.sa-kuva-105711">"Sotasaalista ja kaatuneita Raatteen tiellä."</a> -valokuvaa
            </p>
            <ol class="content-list" type="1">
              <li>Ovatko kuvassa olevat kaatuneet suomalaisia vai neuvostoliittolaisia?
              </li>
              <li>Mihin valokuvaaja on halunnut keskittyä valokuvassa? Miksi?
              </li>
              <li>Eläydy kuvassa näkyvän suomalaissotilaiden ja neuvostosotilaiden kokemukseen viimeisen vuorokauden ajalta ennen valokuvassa näkyvää tilannetta. Kirjoita molempien henkilöiden näkökulmasta kirje kotiin.
              </li>
            </ol>
          </div>
        </div>
      </div>
      <div class="panel panel-default">
        <div class="panel-heading" role="tab" id="heading-talvisodan-kuva">
          <h3 class="panel-title">
            <a class="collapsed" role="button" data-toggle="collapse" data-parent="#accordion-tehtavaideat" href="#talvisodan-kuva">
              Talvisodan kuva aineistopaketin perusteella
            </a>
          </h3>
        </div>
        <div id="talvisodan-kuva" class="panel-collapse collapse" role="tabpanel" aria-labelledby="heading-talvisodan-kuva">
          <div class="panel-body">
            <h4>Tehtävä 1</h4>
            <p>Tarkastele aineistopaketin valokuvia kokonaisuutena ja pohdi millainen kuva talvisodasta sinulle välittyy. Perustele vastauksesi.
            </p>
            <p>Vinkki: pohdi aineistoja lähdekriittisesti esimerkiksi alla olevien kysymysten avulla.
            </p>
            <ol class="content-list" type="1">
              <li>Kuka valokuvat on ottanut?
              </li>
              <li>Millaisia teemoja kuvissa esitetään?
              <ul class="content-list">
                <li>Mitä ja keitä on päätetty kuvata (kenen historiaa valokuvat kuvaavat)?</li>
                <li>Millainen kuva näistä ihmisistä ja sodasta esitetään</li>
                <li>Mitä on jätetty kuvaamatta?</li>
                <li>Miksi?</li>
              </ul>
              </li>
              <li>Kenelle valokuvat on tarkoitettu?
              </li>
            </ol>
            <p>Pohdi lopuksi, miten aineistopaketin tapa esitellä jatkosotaa eroaa
            </p>
            <ol class="content-list" type="1">
                <li>aiemmasta käsityksestäsi</li>
                <li>oppikirjan kuvauksesta</li>
            </ol>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>
<!-- END of: custom - content/talvisota_fi.phtml -->
