<!-- START of: custom - content/tyolaiset_sv.phtml -->
<?php $this->headTitle('Arbetarna börjar påverka samhällsfrågorna i Finland');?>
<?php if ($this->resolver('luokkahuoneBegin_fi.phtml')): ?>
  <?=$this->render('luokkahuoneBegin_fi.phtml')?>
<?php endif; ?>

<button class="goBack" onclick="goBack()"><i class="fa fa-arrow-left" aria-hidden="true"></i> <?=$this->transEsc('navigate_back') ?></button>

<h2>Arbetarna börjar påverka samhällsfrågorna i Finland</h2>
<p><strong>Materialet har sammanställts av</strong> Iris Olavinen & Jani Kaunismäki / Arbetararkivet
</p>
<p>Under Finlands autonomi fanns makten hos Rysslands kejsare och ständerna – bönderna, borgarna, prästerna och adeln. Fram till att Europas modernaste folkrepresentation grundades i Finland 1906, representerades folket av ständerna på ståndslantdagen.
</p>
<p>Arbetararkivets materialpaket berättar historien om hur den klass som stod utanför ständerna och som utförde tungt fysiskt arbete vaknade upp och började kräva rättigheter och delaktighet i beslutsfattandet. Arbetarnas massor väcktes upp, dvs. agiterades, av aktiva personer som hade inspirerats av socialismen och arbetarideologin.
</p>
<p>Finlands arbetarparti grundades 1899 och började främja den missgynnade befolkningsdelens ställning och kräva delaktighet i den riksomfattande politiska verksamheten. Partiet krävde även möjlighet för folket att påverka lokala frågor.
</p>
<p>Arbetararkivets samtliga fotografier har CC BY-NC-ND 4.0. -licens (bilden får delas, distribueras och visas. Källa och upphovsman till materialet ska alltid nämnas. Materialet får inte redigeras.)
</p>
<h3>Målgrupp:</h3>
<div class="panel-group" id="accordion-kohderyhma" role="tablist" aria-multiselectable="true">
  <div class="panel panel-default">
    <div class="panel-heading" role="tab" id="heading-ylakoulu">
      <h4 class="panel-title">
        <a role="button" data-toggle="collapse" data-parent="#accordion-kohderyhma" href="#ylakoulu">
          Högstadier: <small><strong>historia</strong></small>
        </a>
      </h4>
    </div>
    <div id="ylakoulu" class="panel-collapse collapse" role="tabpanel" aria-labelledby="heading-ylakoulu">
      <div class="panel-body">
        <p>Läroämnens innehållsområden:</p>
        <ul class="content-list">
          <li>Historia: I1 Industrisamhällets uppkomst och utveckling, I2 Människor förändrar världen, I3 Finland skapas, byggs och försvaras
          </li>
        </ul>
      </div>
    </div>
    </div>
      <div class="panel panel-default">
    <div class="panel-heading" role="tab" id="heading-lukio">
      <h4 class="panel-title">
        <a role="button" data-toggle="collapse" data-parent="#accordion-kohderyhma" href="#lukio">
          Gymnasier: <small><strong>historia</strong></small>
        </a>
      </h4>
    </div>
    <div id="lukio" class="panel-collapse collapse" role="tabpanel" aria-labelledby="heading-lukio">
      <div class="panel-body">
        <p>Läroämnens kurser:</p>
        <ul class="content-list">
          <li>Historia: HI1 Människan i en föränderlig omvärld, HI3 Det självständiga Finlands historia
          </li>
        </ul>
      </div>
    </div>
  </div>
</div>
<div class="panel panel-default">
  <div class="panel-body">
    <h4>Diskussionsförslag på lektioner:</h4>
    <ul class="content-list">
      <li>Varför ville arbetarna vara med och påverka Finlands samhällsfrågor?
      </li>
      <li>Med vilka medel försökte arbetarna påverka före lantdagsreformen?
      </li>
      <li>Och efter lantdagsreformen?
      </li>
    </ul>
  </div>
</div>

<ul class="nav nav-tabs help-tabs nav-aineistopaketit">
  <li class="active"><a data-toggle="tab" href="#aineistopaketti">Material</a>
  </li>
<?php /*
  <li><a data-toggle="tab" href="#tehtavaideat">Tehtäväideat</a>
  </li>
*/?>
</ul>
<div class="tab-content">
  <div id="aineistopaketti" class="tab-pane fade in active">
    <?=$this->userlistEmbed(['id' => 65, 'view' => 'grid', 'title' => false,  'description' => false,  'date' => false, 'allowCopy' => true])?>
  </div>
<?php /*
  <div id="tehtavaideat" class="tab-pane fade">
    <p>Tehtäväideat on suunniteltu antamaan ideoita siihen, kuinka voit tarkastella aineistopakettia. Voit lähestyä aihetta valitsemalla tehtävistä yhden tai useamman. Tehtävät voi tehdä yksilö-, pari- tai ryhmätehtävinä. Muokkaa tehtäväideoita eri oppiasteisiin ja oppiaineisiin haluamallasi tavalla.
    </p>
    <p>Mikäli haluat tilata Työväen Arkiston aineistopaketin valokuvasta tarkempilaatuisen version opetuskäyttöön, ota yhteyttä Työväen Arkistoon: info(at)tyark.fi. Tilaus on opettajille maksuton.
    </p>
    <div class="panel-group" id="accordion-tehtavaideat" role="tablist" aria-multiselectable="true">
      <div class="panel panel-default">
        <div class="panel-heading" role="tab" id="heading-valokuvat">
          <h3 class="panel-title">
            <a class="collapsed" role="button" data-toggle="collapse" data-parent="#accordion-tehtavaideat" href="#valokuvat">
              Valokuvat lähteinä - kuvien tulkintaa ja analysointia
            </a>
          </h3>
        </div>
        <div id="valokuvat" class="panel-collapse collapse" role="tabpanel" aria-labelledby="heading-valokuvat">
          <div class="panel-body">
            <h4>Tehtävä 1</h4>
            <p>Tarkastele kuvaa <a target="_blank" href="/Record/sa-kuva.sa-kuva-116287">”Työläisiä ryhmäkuvassa 1900-luvun alussa”</a>. Lue myös kuvatekstit ja muistiinpanot.
            </p>
            <ol class="content-list" type="1">
              <li>Missä ja milloin kuva on otettu?
              </li>
              <li>Keitä on kuvassa?
              </li>
              <li>Pohdi, miksi kuva on otettu.
              </li>
              <li>Tutki työläisten vaatteita. Millaisia eroja huomaat vaatetuksessa? Päättele vaatetuksesta, missä asemassa kuvan henkilöt ovat työskennelleet.
              </li>
              <li>Kuvassa on myös kaksi lasta. Minkä ikäisiä he ovat mahdollisesti olleet? Pohdi, miksi heidät on palkattu töihin.
              </li>
            </ol>
            <h4>Tehtävä 2</h4>
            <p>Tutki aineistopaketin <a target="_blank" href="/List/706344">valokuvia mielenosoituksista ja lakoista</a>. Lue myös kuvatekstit ja muistiinpanot valokuvista.
            </p>
            <ol class="content-list" type="1">
              <li>Mistä syistä työläiset lakkoilivat tai järjestivät mielenosoituksia aineistopaketin valokuvien perusteella?
              </li>
              <li>Mistä syistä nykypäivänä järjestetään mielenosoituksia tai lakkoja?
              </li>
            </ol>
          </div>
        </div>
      </div>
      <div class="panel panel-default">
        <div class="panel-heading" role="tab" id="heading-palvelija">
          <h3 class="panel-title">
            <a class="collapsed" role="button" data-toggle="collapse" data-parent="#accordion-tehtavaideat" href="#palvelija">
              Suomen Palvelijain Liitto ja palvelijan asema
            </a>
          </h3>
        </div>
        <div id="palvelija" class="panel-collapse collapse" role="tabpanel" aria-labelledby="heading-palvelija">
          <div class="panel-body">
            <h4>Tehtävä 1</h4>
            <p>Tutki kuvaa <a target="_blank" href="/Record/ta_ah.M011-1240417">”Suomen Palvelijain Liiton viides edustajakokous Helsingissä Työväentalon E-salissa 17.-19.6.1917”</a>. Lue myös kuvatekstit ja muistiinpanot.
            </p>
            <ol class="content-list" type="1">
              <li>Missä ja milloin valokuva on otettu?
              </li>
              <li>Keitä on kuvassa?
              </li>
              <li>Mitä uudistuksia Palvelijain Liitto vaati palvelijoille?
              </li>
            </ol>
            <h4>Tehtävä 2</h4>
            <p>Lue alla oleva katkelma ”Maalaispalvelijain olosuhteet” -artikkelista, joka ilmestyi Palvelijatarlehdessä vuonna 1906. Artikkelin on kirjoittanut lehden päätoimittaja Miina Sillanpää. Löydät koko lehden digitoituna <a target="_blank" href="https://digi.kansalliskirjasto.fi/aikakausi/binding/976970?page=1">täältä</a>.
            </p>
            <p><i>”Etenkin naispalvelijoilla on mitättömän pieni palkka, katsoen siihen paljoon työhön joka heidän on tehtävä. Tavallisissa talonpoikastaloissa, joissa on vaan yksi palvelija, saa hän nousta aamusella tuntia aiemmin muita, sillä kahvit täytyy olla valmiina siksi kuin miehet nousevat. Karjanhoito ottaa aamuajan, ja sitten on ulkotöitä, joita myöskin naispalvelijan täytyy kesäisisin toimittaa. Ruoka-ajat saa siivota huoneita, pestä astioita sillä aikaa kuin miehet levollisesti nukkuvat ruokalepoaan. Illalla on palvelijalla työtä tunniksi tai pariksi sen jälkeen kuin miehet jo ovat lopettaneet toimensa.</i>
            </p>
            <p><i>Ja tämä on yhtäläistä suvet, talvet, pyhät ja aret, niin ettei siinä ole suuria muutoksia. Ja tästä annetaan palkkaa 60mk., paikoittain 150 vuodessa, joka jo on suuri palkka. Ja tästä pienestä palkasta täytyy palvolijan [sic!] työskennellä niin ahkeraan, ettei ehdi vuoden pitkään hameensa helmaa korjaamaan, tai sukkiansa parsimaan, vaan ne hän saa teettää, jos mieli ehjänä käydä.”</i> (Sillanpää, Miina, Maalaispalvelijain olosuhteet, Palvelijatarlehti n:o 1-2, 1906, s.7)
            </p>
            <ol class="content-list" type="1">
              <li>Mitä työtehtäviä maalaispalvelijalla oli 1900-luvun alussa?
              </li>
              <li>Millaista työ oli tekstikatkelman mukaan?
              </li>
              <li>Keitä tekstissä mainitut miehet olivat?
              </li>
              <li>Mitä työtä miehet ovat tehneet?
              </li>
              <li>Miltä miesten työ/asema talonpoikaistalossa vaikuttaa verrattuna naispuolisen maalaispalvelijan työhön?
              </li>
              <li>Selvitä Palvelijatarlehden taustaa. Kenelle lehti oli suunnattu ja miksi? Löydät koko lehden digitoituna <a target="_blank" href="https://digi.kansalliskirjasto.fi/aikakausi/binding/976970?page=1">täältä</a>.
              </li>
              <li>Palvelijatarlehden päätoimittajana toimi Miina Sillanpää. Selvitä verkkoa käyttäen kuka hän oli.
              </li>
              <li>Pohdi, kuinka luotettava lähde palvelijoiden olosuhteista kyseinen lehti on. Perustele.
              </li>
            </ol>
          </div>
        </div>
      </div>
      <div class="panel panel-default">
        <div class="panel-heading" role="tab" id="heading-vastaukset">
          <h3 class="panel-title">
            <a class="collapsed" role="button" data-toggle="collapse" data-parent="#accordion-tehtavaideat" href="#vastaukset">
              Vastaukset
            </a>
          </h3>
        </div>
        <div id="vastaukset" class="panel-collapse collapse" role="tabpanel" aria-labelledby="heading-vastaukset">
          <div class="panel-body">
            <h4>Valokuvat lähteinä - kuvien tulkintaa ja analysointia</h4>
            <h5>Tehtävä 2</h5>
            <ol class="content-list" type="1" start="2">
              <li>Mielenosoituksia mm. yleisen ja yhtäläisen äänioikeuden puolesta kesällä 1905, suurlakko syksyllä 1905 venäläistämistoimien vuoksi, kunnallisen äänioikeuden vaatimus 1908, vaatimus 8 tunnin työpäivästä vuonna 1917.
              </li>
            </ol>
            <h4>Suomen Palvelijain Liitto ja palvelijan asema</h4>
            <h5>Tehtävä 2</h5>
            <ol class="content-list" type="1">
              <li>Aamutoimet, karjanhoito, muut ulkotyöt, siivoaminen, ruuanlaitto jne.
              </li>
              <li>Ympäri vuoden raskasta, pitkiä päiviä, ei säännöllistä ruokataukoa, ei ehdi korjata vaatteita.
              </li>
              <li>Todennäköisesti talonpoikastalon miespalvelijoita.
              </li>
              <li>Miehet ovat tehneet raskaita ulkotöitä, joissa naispalvelijat ovat kesäisin avustaneet.
              </li>
              <li>Tekstikatkelman perusteella naisten työ vaikuttaa raskaammalta kuin miesten.
              </li>
              <li>Työläisnaisille suunnattu lehti, joka pyrki parantamaan työläisnaisten asemaa levittämällä tietoa työläisten oloista Suomessa ja maailmalla.
              </li>
              <li>Sillanpää oli aloittanut uransa piikana ja palvelijana. Yksi Suomen ensimmäisiä naiskansanedustajia 1907 ja Suomen ensimmäinen naispuolinen ministeri 1920-luvulla. Ajoi erityisesti palvelijoiden ja yksinäisten naisten asioita.
              </li>
              <li>Lehden tekijät itsekin palvelijoita tai entisiä palvelijoita. Vahva poliittinen agenda taustalla: halu nostaa asia julkiseen keskusteluun, jotta saavutettaisiin muutoksia. Ei siis puolueeton lehti.
              </li>
            </ol>
          </div>
        </div>
      </div>
    </div>
  </div>
*/?>  
</div>
<!-- END of: custom - content/tyolaiset_sv.phtml -->
