<!-- START of: finna - Helpers/nkrRestrictedRecordPermission.phtml -->
<? "status: " . var_export($this->status, true) . ", call: " . var_export($this->callApi, true) . ", not submitted: " . var_export($this->notSubmitted, true) ?>
<?php if (!$this->user): ?>
  <div class="alert alert-info authorization-notification">
    <p><?= $this->translate('nkr_restricted_record_note') ?></p>
    <p><a href="<?=$this->url('myresearch-userlogin')?>" data-lightbox title="<?=$this->transEsc("Login")?>"><i class="fa fa-sign-in"></i> <?=$this->transEsc("Login")?></a></p>
  </div>
<?php else: ?>
  <? if ($this->notSubmitted): ?>
    <?php $this->headScript()->appendFile('finna-nkr.js'); ?>
    <?php
      $fn = $this->callApi ? 'initCheckPermission' : 'initApplyPermission';
      $setupJS = <<<JS
$(document).ready(function() {
   finna.nkr.{$fn}("{$this->id}");
});
JS;
      $this->headScript()->appendScript($setupJS);
    ?>  
  <? endif ?>
  <div class="alert alert-info authorization-notification check-permission nkr-status nkr-status-not-submitted<?= $this->status === null || $this->status !== 'not-submitted' ? ' hide' : ''?>" data-id="<?=$this->escapeHtmlAttr($this->id)?>">
    <p class="txt"><?= $this->translate('nkr_restricted_record_note') ?></p>
    <p class="register"><a class="btn btn-primary"><?=$this->translate('nkr_register')?></a></p>
  </div>
  <? if (!$this->translationEmpty("nkr_permission_request_status_submitted")): ?>
    <div class="alert alert-info authorization-notification nkr-status nkr-status-submitted<?= $this->status === null || $this->status === 'not-submitted' ? ' hide' : ''?>">
      <p class="txt"><?= $this->transEsc("nkr_permission_request_status_submitted") ?></p>
    </div>
  <? endif; ?>
<? endif; ?>
<!-- END of: finna - Helpers/nkrRestrictedRecordPermission.phtml -->
