<!-- START of: finna - Helpers/nkrRestrictedRecordPermission.phtml -->
<? if ($this->notSubmitted): ?>
<?php $this->headScript()->appendFile('finna-nkr.js'); ?>
<?php
$setupJS = <<<JS
$(document).ready(function() {
   finna.nkr.initCheckPermission("{$this->id}");
});
JS;
    $this->headScript()->appendScript($setupJS);
?>
<div class="alert alert-info authorization-notification check-permission" data-id="<?=$this->escapeHtmlAttr($this->id)?>">
    <p class="txt"><?= $this->translate('nkr_restricted_record_note') ?></p>
    <p class="link"><a href="<?= $this->url($this->route, ['id' => $id])?>" class="btn btn-primary"><?=$this->translate('nkr_restricted_record_show')?></a></p>
</div>
<? else: ?>
<div class="alert alert-info authorization-notification">
    <p class="txt"><?= $this->status ?></p>
</div>
<? endif; ?>
<!-- END of: finna - Helpers/nkrRestrictedRecordPermission.phtml -->
