<!-- START of: finna - Helpers/nkrRestrictedRecordNote.phtml -->
<div class="alert alert-info authorization-notification">
    <p><?= $this->translate('nkr_restricted_record_note_html') ?></p>
    <p><a href="<?= $this->url($this->route, ['id' => $id])?>" class="btn btn-primary"><?=$this->translate('nkr_restricted_record_show')?></a></p>
</div>
<!-- END of: finna - Helpers/nkrRestrictedRecordNote.phtml -->
