<?php if ($tabUrl = $this->recommend->getTabUrl()): ?>
<!-- START of: finna - Recommend/LearningMaterial.phtml -->
<div class="learning-material-recommendation alert alert-info">
  <p>Etsitkö avoimia oppimateriaaleja? Siirry <a href="<?= $tabUrl ?>">Avointen oppimateriaalien välilehdelle</a> ja saat runsaammin rajausmahdollisuuksia.</p>
</div>
<!-- END of: finna - Recommend/LearningMaterial.phtml -->
<?php endif; ?>
