<!-- START of: finna - search/home/home-1.phtml -->
<div class="news-finna">
    <?= $this->feed("news-finna"); ?>
</div>
<div class="finna-nostot">
<a class="finna-nosto" href="<?=$this->url('search-streetsearch')?>?go=1">
    <picture>
        <source media="(max-width: 480px)" srcset="<?=$this->imageLink('finna-street-banner-box-en.png')?>">
        <img src="<?=$this->imageLink('finna-street-banner-en.png')?>" alt="Finna Street – Uncover historical images of where you are!">
    </picture>
</a>
</div>
<!-- END of: finna - search/home/home-1.phtml -->
