<!-- START of: finna - search/home/home-1.phtml -->
<div class="news-finna">
    <?= $this->feed("news-finna"); ?>
</div>
<div class="finna-nostot">
<a class="finna-nosto" href="<?=$this->url('content-page', ['page' => 'luokkahuone'])?>">
    <picture>
        <source media="(max-width: 480px)" srcset="<?=$this->imageLink('finna-luokkahuone-banner-box-sv.png')?>">
        <img src="<?=$this->imageLink('finna-luokkahuone-banner-sv.png')?>" alt="Finna Klassrum – varje lärares skattkammare">
    </picture>
</a>

<a class="finna-nosto" href="<?=$this->url('search-streetsearch')?>?go=1">
    <picture>
        <source media="(max-width: 480px)" srcset="<?=$this->imageLink('finna-street-banner-box-sv.png')?>">
        <img src="<?=$this->imageLink('finna-street-banner-sv.png')?>" alt="Finna Street – Upptäck historiska bilder av var du är!">
    </picture>
</a>
</div>
<!-- END of: finna - search/home/home-1.phtml -->
