<!-- START of: finna - Related/WorkExpressions.phtml -->
<?php $records = $this->related->getResults(); ?>
<?php if (!empty($records)): ?>
  <div class="work-expressions">
    <h4><?=$this->transEsc('work_expressions_title')?></h4>
    <ul class="list-group">
      <?php foreach ($records as $data): ?>
        <li class="list-group-item">
          <a href="<?=$this->recordLink()->getUrl($data)?>">
            <?=$this->escapeHtml($data->getTitle())?>
          </a>
          <div class="details">
            <?=$this->record($data)->getFormatList();?>
            <?php $authors = $data->getPrimaryAuthors(); if (!empty($authors)): ?>
              <br/><?=$this->transEsc('by')?>: <?=$this->escapeHtml($authors[0]);?><?php if (count($authors) > 1): ?> <?=$this->transEsc('more_authors_abbrev')?><?php endif; ?>
            <?php endif; ?>
            <?php $pubDates = $data->getPublicationDates(); if (!empty($pubDates)): ?>
              <br/><?=$this->transEsc('Published')?>: (<?=$this->escapeHtml($pubDates[0])?>)
            <?php endif; ?>
          </div>
        </li>
      <?php endforeach; ?>
    </ul>
  </div>
<?php endif; ?>
<!-- END of: finna - Related/WorkExpressions.phtml -->
